### PR TITLE
Apply @szepeviktor's fix to 1.x

### PR DESCRIPTION
**Pull request by jarednova**
Test to apply #2257 to the current master ...

### CODE REVIEW

**Comment by szepeviktor** [comment]
Above lightspeed :)

But

> pecl/pcov requires PHP (version >= 7.1.0), installed version is 5.6.40

**Comment by jarednova** [comment]
WOW! That just shaved off like 40% of test execution time! Holy moly!

**Comment by jarednova** [comment]
... easy enough to make it apply to only PHP 7

**Comment by szepeviktor** [comment]
> /home/travis/.travis/functions: line 109: [: 7.4: integer expression expected

😿 

Try `if [ "$(phpenv version-name)" != 5.6 ];`

**Pull request merged**
