### PR TITLE
Adding support for loading views without twig extension

### PR DESCRIPTION
**Pull request by connorjburton**
**Ticket**: #933
**Reviewer**: @jarednova
#### Issue

Can't load views without specifying `.twig` extension
#### Solution

Check if the filename is a string, check if the template doesn't exist (if someone wants to load `myview` without an extension and the file exists, then we should let them), then check if the filename doesn't end in `.twig` (reverse the string as it's quicker). If all that is true, we add `.twig` on the filename.
#### Impact

Little bit slower
#### Usage

`{% include 'views/hello' %}`
#### Considerations

This only works for strings, not arrays of views. I think we should refactor this method to be recursive, I think it would make more sense. Let me know if you want me to do this. 
#### Testing

None included

### CODE REVIEW

**Comment by connorjburton** [comment]
Tests are failing for some reason, will come back to this

**Comment by connorjburton** [comment]
Should be okay to merge @jarednova

**Comment by connorjburton** [comment]
Not sure how coverage has gone down here?

**Comment by jarednova** [comment]
I've noticed that Coveralls can throw back weird numbers on occasion — you def. have coverage on those lines. Before merging I want to make sure this works with arrays so that we don't end up with a situation where not adding `.twig` _sometimes_ works.

I could see this being accomplished through a private `maybe_add_twig_extension` method (sorry for being so prescriptive) so the `choose_template` method doesn't get too unwieldy. That said, use your judgement — almost there!

**Comment by jarednova** [comment]
I just want to confirm the expected functionality here...

If I try to load `{% include 'views/hello' %}` and the file `views/hello` exists, the content of `views/hello` will be used.

If I try to load `{% include 'views/hello' %}` and the file `views/hello` DOES NOT exists, the content of `views/hello.twig` will be used (if it exists).

**Comment by jarednova** [comment]
@lggorman and I never had much luck with this guy, going to close for now and pursue a diff't solution to #933

**Pull request closed without merging**
