### PR TITLE
Filter for not forcing the WordPress way of get_posts.

### PR DESCRIPTION
**Pull request by palmiak**
**Ticket**: #1987

## Issue
Adds an additional filter that will give devs a chance to use get_posts in classic Timber way or in WP way.

## Solution
Adds an extra if + filter that can be set to true or false.

## Impact
It should solve issues like #1987 and on the hand will provide with quite easy way to solve #1812 

## Usage Changes
```
add_filter( 'timber/post_getter/wp_get_posts', '__return_true' );
add_filter( 'timber/post_getter/wp_get_posts', '__return_false' );
```

## Considerations
This is a temporary fix until we'll figure out what to do with `Timber::get_posts()`.

Also - I'm not sure about the filter name. Making those name is hard :(

## Testing
I added add_filter in tests so the test would run in WP way.

### CODE REVIEW

**Comment by palmiak** [comment]
I like the mirror name 😀 You should add to your CV "senior filter and
variable name creator"

wt., 7 maj 2019, 08:25 użytkownik Lukas Gächter <notifications@github.com>
napisał:

**Comment by palmiak** [comment]
I see that there are travis-errors but I think they are related with #1990

**Comment by gchtr** [comment]
@palmiak Oh yes! I opened #1994 to fix this.

**Comment by mibu31** [comment]
This is a great solution, please resolve/merge 👍

**Pull request merged**
