### PR TITLE
ref #2024 -- patch for custom MenuItems

### PR DESCRIPTION
**Pull request by jarednova**
**Ticket**: #2024 #1988 

## Issue
Inadvertent breaking change introduced by new `Timber\MenuItem` constructor definition in `1.10`

## Solution
Set a default `null` value for the menu

## Impact
Filtering CSS classes (and other things that a user might do with menu info) won't work

## Usage Changes
None

## Considerations
Probably something that we don't need to bring into 2.x

## Testing
No new tests

### CODE REVIEW

**Comment by gchtr** [comment]
Yeah, I totally missed that the second parameter should probably be optional.

> Probably something that we don't need to bring into 2.x

I’m not sure about this. I – without thinking too much about it – assumed that a `MenuItem` always only exists in combination with a `Menu` object. But when we have a public `MenuItem` class, shouldn’t it be possible to create an instance without the knowledge of a parent `Menu` object? Maybe we need to keep this.

**Comment by jarednova** [comment]
Fair point. And honestly easier to keep than selectively remove/isolate it

**Comment by jarednova** [comment]
Wooohooo, tests pass! @palmiak or @gchtr could I get a quick review so I can merge?

**Comment by jarednova** [comment]
@gchtr definitely. I had started a test locally that I can add to this branch

**Comment by jarednova** [comment]
Test, added + merged!

**Pull request merged**
