### PR TITLE
2.x factories

### PR DESCRIPTION
**Pull request by szepeviktor**
Let's have a PR for Factories.

### CODE REVIEW

**Comment by szepeviktor** [comment]
```
There was 1 error:

1) TestTimberUser::testIDDataType

Error: Call to protected Timber\User::__construct() from context 'TestTimberUser'

tests/test-timber-user.php:12
```

**Comment by jarednova** [comment]
I think we're good here @acobster @gchtr ? Unless there's something I'm missing I think we could pull this in and proceed with THE PURGE #2323. 

The only other PR to consider (at least that I saw) was #2293. Let me know if that needs to be resolved/merged first before we merge with #1617 or if it can come in after direct to 2.x

**Review by jarednova — DISMISSED** [review]

**Comment by acobster** [comment]
There are a few other things noted in the checklist in #2073 (#2292, #1863, #2333) but these are all improvements on top of what I think is a pretty strong foundation here. We should also do a final pass over all the tests that are currently skipped at some point. And just for completeness's sake, #2073 still needs to be merge in, but I think that should come after those improvements.

@szepeviktor where did you see that test failure? Travis seems happy...

Barring any objections from @gchtr, I say let's go for it.

**Comment by szepeviktor** [comment]
> @szepeviktor where did you see that test failure? Travis seems happy...

That was 8 months ago 🐈

**Comment by acobster** [comment]
> That was 8 months ago :cat2: 

lol, is it Friday yet?

**Review by gchtr — APPROVED** [review]

**Comment by gchtr** [comment]
@jarednova @acobster I’d say, let’s merge this in and then work on remaining tasks against the `2.x` branch. If any pull request is still against `2.x-factories`, it will be automatically updated to be pulled against `2.x`.

From what I can tell, #2073 still gives a very up-to-date view over the remaining tasks. I think apart from THE PURGE (#2323), these are mostly the only remaining blocking tasks that we need to work on before we could release an alpha or a beta version, right?

While we can test the first version and resolve issues that might still surface there, we can also work on the other remaining tasks, like documentation, type declarations, etc.

I can check for merge conflicts with #2073 once this pull request is merged into `2.x`.

@acobster I’ll leave it to you to do the merge.

**Comment by acobster** [comment]
Alright! Merging momentarily.

> these are mostly the only remaining blocking tasks that we need to work on before we could release an alpha or a beta version, right?

Yeah, I've done my best to keep #2073 up to date with everything we need to tackle before 2.0.

And actually, IMO there's no reason we couldn't create an alpha release now. There will be one or two breaking changes thereafter (e.g. type declarations, PHP req), but that's what alpha releases are for :slightly_smiling_face:

**Comment by szepeviktor** [comment]
# 🎉

**Comment by jarednova** [comment]
Now that's a merge!

**Pull request merged**
