### PR TITLE
Introduce Timber::get_term_by() method

### PR DESCRIPTION
**Pull request by jarednova**
**Ticket**: #2359 

## Issue
There's `Timber::get_post_by`, `Timber::get_user_by` ... — let's wrap it up with `get_term_by`

## Solution
Copy the pattern from other get_x_by and apply it!

## Impact
More poly-morphizing

## Usage Changes
- [x] Need to add docs example

## Considerations
@acobster suggested in the write-up that we can improve upon WP functionality by better processing the `taxonomy` value. I agree. Even when writing the tests I was thrown off by its requirement even when there's only one term with a certain name.
- [x] Handle for what happens when a taxonomy isn't supplied

## Testing
Wrote a new test `testTermBy`

### CODE REVIEW

**Review by gchtr — APPROVED** [review]
This looks all good from my side, but I’d be glad if @acobster could also look over it.

**Comment by jarednova** [comment]
@acobster just wanted to make sure you had a chance to take a gander at this on.

In regards to merges (on this and others). Travis support is totally useless. I think we should plan to merge based on the results of local tests. If they aren't able to get things back running by end of the week, I'm going to look into migrating to GitHub Actions.

**Comment by acobster** [comment]
@jarednova noted. I usually run the full suite locally before merging or creating a PR anyway.

**Comment by acobster** [comment]
also, this did fall off my radar so thanks for pinging me! Hope to get to it this week.

**Comment by jarednova** [comment]
Finally got Travis tests going (OMFG) and needed to adjust a few tests to match w most up-to-date return types and WP stuff. @acobster remember me? Hi! 👋 . This one is pretty non-controversial so I want to give a little time in case you'd like to do a final look

**Comment by acobster** [comment]
@jarednova hmmmm your name rings a bell from some time before the decade or so I've spent doomscrolling in my cave....Hi! Taking a look at this now.

**Review by acobster — APPROVED** [review]
Looks great!

**Comment by jarednova** [comment]
Ahhh, we were so young!

**Pull request merged**
