### PR TITLE
Add PHP 8.0/8.1 to Timber 1.x matrix

### PR DESCRIPTION
**Pull request by nlemoine**
Related:
- https://github.com/timber/timber/issues/2580
- https://github.com/timber/timber/issues/2548

### CODE REVIEW

**Comment by gchtr** [comment]
@nlemoine Thanks a lot for taking this on. Now, what do we need to move this out of draft status?

**Comment by nlemoine** [comment]
Hey @gchtr 

I had some weird issues running tests (some "segmentation fault" with no valuable message). I solved them and finally almost fixed the tests. As you can see, some pass, some don't :
- PHP 7.4 | WP latest (MS) : some problems with the WP-CLI cache clearing
- PHP 7.4 | WP latest (with coverage) : I don't get why the clover file isn't readable, I didn't try much

Would you be interested to take this PR over?

**Comment by gchtr** [comment]
@nlemoine I think this is ready now. I added some fixes for PHP 8.1 deprecation warnings, e.g. when cropping images without rounding the new width and height first.

And I found the fix for the missing clover.xml file in [`a7fdf59` (#2638)](https://github.com/timber/timber/pull/2638/commits/a7fdf59bf3e22dd548e0ead6936abcabdfec2d82).

There’s still a couple of warnings, but they are mostly related to WordPress itself, where we have no control.

Just need a final approval so we can merge this in.

**Comment by nlemoine** [comment]
Good job @gchtr!

**Review by jarednova — APPROVED** [review]

**Comment by jarednova** [comment]
@gchtr @nlemoine I confirmed that the tests all pass with the merge of #2640. I was able to do a brief review of the code and new testing elements and am so humbled by how much cleaner and more sophisticated this leaves things. Lots of green checks!!!!

**Pull request merged**
