### PR TITLE
Namespacing

### PR DESCRIPTION
**Pull request by connorjburton**
**Ticket**: #869
**Reviewer**: @jarednova 

#### Issue

Modernising Timber to use namespaces

#### Solution

A lot of code changes...

#### Impact

Is fully backwards compatible, I was thinking of using a trait, but as the list of classes that needed backwards compatibility is atomic, it was easier just to create a function.

#### Usage

Yes, too much to list here. See considerations.

#### Considerations

We need to update all the docs to represent this new change.

#### Testing

Tests need updating with this.

For now to test you can do the following `composer require timber/timber:dev-dev-namespacing`

### CODE REVIEW

**Comment by jarednova** [comment]
Awesome! I'll start my review tonight

**Comment by connorjburton** [comment]
Good progress so far!

**Comment by jarednova** [comment]
@connorjburton: Woohoo! everything finally passes! Before merging I want to test this in a local build which I should be able to do tomorrow

**Comment by connorjburton** [comment]
Oh my days! Made my week. Looks like you got the hard end of the stick though, sorry about that :) I'll have a test tonight aswell and will upgrade on a few sites I've done recently to make sure backwards compatibility works perfectly.

**Comment by jarednova** [comment]
@connorjburton. I feel very confident about where this stands. I've put a few themes through the ringer and have yet to find any other issues. Once #955 is merged into this (I've assigned to you), I'm ready to merge this unless you've found any other issues on your end

**Comment by connorjburton** [comment]
Brilliant, I will review #955 tonight. I probably won't be available after tonight until early next week but i'll make sure #955 gets merged tonight.

Thank you for all the work!

**Comment by connorjburton** [comment]
I have also moved all other tasks on the `1.0.0` milestone to `> 1.0.1` - as we are a bit behind it'd be good to get `1.0.0` released on packagist and wp.org once we merge.

**Comment by jarednova** [comment]
@connorjburton — that plan works for me!

**Comment by connorjburton** [comment]
Awesome, been merged! What is schedule for release on packagist and wp.org?

**Comment by jarednova** [comment]
@connorjburton — I just pushed to Packagist. My plan was to wait a few days for any bugs to surface and then release on Tuesday May 3 to WordPress.org!

**Comment by connorjburton** [comment]
Aha, good idea. Thanks for the info

**Pull request merged**
