### PR TITLE
2x/no factories

### PR DESCRIPTION
**Pull request by jarednova**
Working to resolve errors in #1617 merge ...

### CODE REVIEW

**Comment by jarednova** [comment]
@szepeviktor I was wondering if I could get your help understanding this error we're seeing in Travis ...

```
PHP Fatal error:  Uncaught Error: Class 'WP_Upgrader_Skin' not found in /home/travis/build/timber/timber/tests/phpstan/wp-cli-stubs-2.2.0.php:873
Stack trace:
#0 /home/travis/build/timber/timber/vendor/composer/ClassLoader.php(444): include()
#1 /home/travis/build/timber/timber/vendor/composer/ClassLoader.php(322): Composer\Autoload\includeFile('/home/travis/bu...')
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass('WP_CLI_Command')
#3 [internal function]: spl_autoload_call('WP_CLI_Command')
#4 /home/travis/build/timber/timber/lib/Integrations.php(23): class_exists('WP_CLI_Command')
#5 /home/travis/build/timber/timber/lib/Integrations.php(17): Timber\Integrations->init()
#6 /home/travis/build/timber/timber/lib/Timber.php(109): Timber\Integrations->__construct()
#7 /home/travis/build/timber/timber/lib/Timber.php(77): Timber\Timber::init()
#8 /home/travis/build/timber/timber/tests/bootstrap.php(15): Timber\Timber->__construct()
#9 /tmp/wordpress/wp-includes/class-wp-hook.php(288): _manually_load_plugin('')
#10 /tm in /home/travis/build/timber/timber/tests/phpstan/wp-cli-stubs-2.2.0.php on line 873
```
Does this make any sense to you? I'm not sure I understand what the WP-CLI Stubs file does. I've been pulling my hair out for the last few hours, is there a fix you can see here?

**Comment by szepeviktor** [comment]
> `PHP Fatal error: Uncaught Error: Class 'WP_Upgrader_Skin' not found in /home/travis/build/timber/timber/tests/phpstan/wp-cli-stubs-2.2.0.php:873`

@jarednova This is a symptom of WP-CLI stubs loaded **before** WordPress core stubs.

Investigating **NOW**...

**Comment by szepeviktor** [comment]
Done.
It was an autoloading issue.
Please merge!

**Comment by szepeviktor** [comment]
> what the WP-CLI Stubs file does

Stubs are Hello World! functions without printing anything :) just there to represent the structure of code.

```php
class Foo
{
  public function helloWorld(): void
  {
    echo "Hello World!\n";
  }
}
```

Stubs

```php
class Foo
{
  public function helloWorld(): void {}
}
```

**Comment by jarednova** [comment]
@szepeviktor blast! thanks for the fix and the explanation. Seems a bad merge conflict resulted in all kinds of fun. Really appreciate you hopping in there — I'll work on cleaning the rest of this up!

**Pull request closed without merging**
