### PR TITLE
ACF Groups docs examples

### PR DESCRIPTION
**Pull request by palmiak**
**Ticket**: https://github.com/timber/timber/issues/1763

#### Issue
Added an example for ACF group usage.

Also if this example is ok I'll create a PR for `meta` in 2.0

### CODE REVIEW

**Comment by jarednova** [comment]
Thanks for the added example @palmiak ! I used it as a chance to also clean up some of the style and using the up-to-date method name

**Comment by palmiak** [comment]
great to hear :) Soon I'll also add this example to `2.x-docs` branch

**Comment by palmiak** [comment]
@jarednova do you know why the groups are not in the documentation? I wanted to close #1763 but I still can't.

**Comment by gchtr** [comment]
@palmiak Yeah, we forgot to rebuild the documentation after the last couple of releases 😅. But they are now live: <https://timber.github.io/docs/guides/acf-cookbook/#group-field>.

I went ahead and closed that issue.

**Pull request merged**
