### PR TITLE
Fixing double image object issue

### PR DESCRIPTION
**Pull request by connorjburton**
**Ticket**: None
**Reviewer**: @jarednova 

#### Issue

I discovered a bug that I haven't seem reported anywhere, I got a fatal error when trying to resize an image.

If you look at the code before/after, you will see that we run `wp_get_image_editor` in both `run_animated_gif` and `run`, the result of that then gets passed into `get_target_sizes` which will then run `wp_get_image_editor` once again, and pass in the result of the previous `wp_get_image_editor`

#### Solution

Firstly I moved the errors further up the method so we catch any errors without throwing fatal errors on production sites.

Then I passed the result of `wp_get_image_editor` into `get_target_sizes` and didn't run that method again once we were in there.

#### Impact

Should fix this bug

#### Usage

No change

#### Considerations

I couldn't find any other mention of this, so maybe it's my setup, but the code didn't look right to me.

#### Testing

None included

### CODE REVIEW

**Comment by connorjburton** [comment]
Couple of issues thrown up by tests, will trace and fix them

**Comment by jarednova** [comment]
cool, I'll bounce it back to you for the test adjustments

**Comment by connorjburton** [comment]
Also added a fix for #1017 in this PR

**Comment by connorjburton** [comment]
Type hinting, I like it. I think I'll go through and add type hinting to everything that I can at some point. (After v1.0.4)

**Comment by jarednova** [comment]
@connorjburton sounds good!

**Pull request merged**
