### PR TITLE
Added filters for plugins to hook into TimberMenu

### LINKED ISSUE #1732: Problems with WooCommerce menu item active element
### Expected behavior
I wanna use `{% if item.current %}active{% else %}nav-item{% endif %}` on WooCommerce menu items. But active element in WooCommerce main page didn't work.
Also tried `{% if item.slug == post.post_name %}active{% endif %}` but same thing, didn't work.
All other page type menu item active elements (page.twig, also single product, product archive, cart and so on) works perfectly, but not WooCommerce main page.
When in example Cart page parent page is WooCommerce main page then Cart active element's also didn't work, but when I use Cart page without parent page then it's working perfectly.

So... If I visit WooCommerce shop main page (/shop), then this page active element didn't work.

### Actual behavior
My menu navigation twig file:
https://i.imgur.com/SlLOito.png

### What version of WordPress, PHP and Timber are you using?
WordPress 4.9.6, PHP 7.2, WooCommerce 3.4.2 and Timber 1.7.1

### AND WHEN I INSTALL WOOCOMMERCE STEP BY STEP:
https://timber.github.io/docs/guides/woocommerce/
THEN I GET 500 ERRORS WHEN I VISIT WOOCOMMERCE MAIN PAGE...

### How did you install Timber? (for example, from GitHub, Composer/Packagist, WP.org?)
WP.org / starter theme from Github

### PR DESCRIPTION
**Pull request by pascalknecht**
Fixes #1732

### CODE REVIEW

**Comment by pascalknecht** [comment]
@jarednova @gchtr Let me know what you think about any problems which might occur from this change. This fixes the problem of WooCommerce not adding a active class as they use a filter to do so. See https://github.com/woocommerce/woocommerce/blob/d0491072e8a7d0a4535db0ec2bae4a6d43ff64fd/includes/wc-page-functions.php#L154 for reference.

**Comment by gchtr** [comment]
This is great! The base problem here is that most of the themes use the `wp_nav_menu()` function to render a navigation menu, and many plugins hook into this function, right? The `wp_nav_menu()` function uses 7 filters:

1. `wp_nav_menu_args` – Filters the arguments used to display a navigation menu.
2. `pre_wp_nav_menu` – Filters whether to short-circuit the wp_nav_menu() output.
3. `wp_nav_menu_container_allowedtags` – Filters the list of HTML tags that are valid for use as menu containers.
4. `wp_nav_menu_objects` – Filters the sorted list of menu item objects before generating the menu's HTML.
5. `wp_nav_menu_items` – Filters the HTML list content for navigation menus.
6. `wp_nav_menu_{$menu->slug}_items` – Filters the HTML list content for a specific navigation menu.
7. `wp_nav_menu` – Filters the HTML content for navigation menus.

Timber doesn’t hook into any of these. But there are quite a few plugins out there that allow users to customize a menu. In #1529, which is kind of related to this, the [WP Menu Cart](https://wordpress.org/plugins/wp-menu-cart/) plugin is mentioned, which hooks into the `wp_nav_menu_{$menu->slug}_items` filter.

I guess with this pull request, it’s quite easy to add support for the `wp_nav_menu_objects` filter. I don’t see any problems with this, currently 👍.

Now, I had a quick thought: The title of this pull request is «Added filters for plugins to hook into TimberMenu». Would it be possible to add support for filters 5 and 6, `wp_nav_menu_items` and `wp_nav_menu_{$menu->slug}_items` as well?

Because these two filter HTML, it might be a little trickier. We could use [a proper Twig example](https://timber.github.io/docs/guides/menus/#displaying-the-menu-items). If I’m not totally mistaken, the following might work. We’d have to provide the `default_args` and the `slug` as properties of `Timber\Menu`.

```twig
{% for item in menu.items %}
    <li class="nav-main-item {{ item.classes|join(' ') }}">
        <a class="nav-main-link" href="{{ item.link }}">{{ item.title }}</a>
        {% if item.children %}
            <ul class="nav-drop">
                {% for child in item.children %}
                    <li class="nav-drop-item">
                        <a href="{{ child.link }}">{{ child.title }}</a>
                    </li>
                {% endfor %}
            </ul>
        {% endif %}
    </li>
    {{ ''|apply_filters('wp_nav_menu_items', '', menu.default_args) }}
    {{ ''|apply_filters('wp_nav_menu_' ~ menu.slug ~ 'items', '', menu.default_args) }}
{% endfor %}
```

Or we could add a custom iterator like we did for the `PostsIterator`, where we would add a hook after the loop has ended:

https://github.com/timber/timber/blob/5101648dd78bdb0b3546864e6674cd284327af9c/lib/PostsIterator.php#L51-L55

I think we don’t need to add support for the other filters. What do you guys think?

**Comment by pascalknecht** [comment]
@gchtr yes exactly. Many plugins hook into this kind of functions. Here a quick feedback to your other suggestions (didn't yet have a deep dive into all filters):

wp_nav_menu_args – Filters the arguments used to display a navigation menu. --> Will not be needed as we don't have menu args in Timber.
pre_wp_nav_menu – Filters whether to short-circuit the wp_nav_menu() output. -->Could maybe be implemented. Not sure if needed though.
wp_nav_menu_container_allowedtags – Filters the list of HTML tags that are valid for use as menu containers. --> Will not be needed
wp_nav_menu_objects – Filters the sorted list of menu item objects before generating the menu's HTML. --> Definitely needed as WooCommerce and other plugins hook into.
wp_nav_menu_items – Filters the HTML list content for navigation menus. --> We haven't digged into these kind of html filters yet. Will probably only be needed by theme developers who need a lot of 3rd party plugins to be compatible. We will need to think about if and how we would want to do that.
wp_nav_menu_{$menu->slug}_items – Filters the HTML list content for a specific navigation menu. --> Same as wp_nav_menu_items
wp_nav_menu – Filters the HTML content for navigation menus. --> Save as wp_nav_menu_items

In my opinion we could probably merge this pull request and have a look at whether or not to implement the other filters in another ticket?

**Comment by gchtr** [comment]
@pascalknecht So we’re on the same page here 👍. I’ll open a separate issue for the compatibility with the two other filters.

For this pull request, I applied coding standards and added comments. I’ll leave it to @jarednova to say whether we also need tests for this and to merge this in.

**Comment by jarednova** [comment]
@pascalknecht this is awesome. Anything that can solve other plugin / WooCommerce compatibility will a huge boon. I think one test to verify the basic behavior would be a good move (def. not worth covering every default property, etc.). After that I think we're good to 👍

**Comment by pascalknecht** [comment]
@jarednova @gchtr  Here we go. Added a little test to check if the filter works. Does that look allright to you?

**Comment by gchtr** [comment]
This looks good to me! Because this is a pull request against the master branch, I’ll leave it to @jarednova to merge this one in.

**Comment by jarednova** [comment]
Good to me as well, thanks @pascalknecht !

**Pull request merged**
