### PR TITLE
Fix typos

### PR DESCRIPTION
**Pull request by szepeviktor**
Found few misspellings.

Please carefully review it.

### CODE REVIEW

**Comment by szepeviktor** [comment]
For the willing contributor: `.typos.toml`
```toml
[files]
extend-exclude = [
    ".git/",
]
ignore-hidden = false

[default]
extend-ignore-re = [
    "Nathan Hass",
]

[default.extend-identifiers]
"field_5ba2c660ed26d" = "field_5ba2c660ed26d"
"PNGs" = "PNGs"
"struc" = "struc"
"testPNGtoJPG" = "testPNGtoJPG"
"testPNGtoWEBP" = "testPNGtoWEBP"
# Known typo
"timber_wp_title_seperator" = "timber_wp_title_seperator"
"tmis" = "tmis"

# Typos
"Github" = "GitHub"
"Wordpress" = "WordPress"
```

**Review by Levdbas — APPROVED** [review]
Looking good! Thank you for your effort!

**Comment by szepeviktor** [comment]
Glad to contribute.

**Comment by Levdbas** [comment]
The new documentation with your changes is now live! Thanks once again @szepeviktor

**Pull request merged**
