### PR TITLE
Add meta property for Timber\Theme

### PR DESCRIPTION
**Pull request by dtvn**
Hello I would like to improve `Timber\Theme` object. 

## Issue
I need to get the theme author name but the current Timber could do that.
Detail: https://github.com/timber/timber/issues/2049

## Solution
Introduce new property for the [Theme](https://github.com/dtvn/timber/blob/master/lib/Theme.php).
```PHP
/**
* @api
* @var array return an array of theme information (ex: author, author URI)
*/
public $meta;
```

Collect data for `$meta` in `init` function:
```PHP
$this->meta = [
	'theme_uri' => $this->theme->get('ThemeURI'),
	'desc' => $this->theme->get('Description'),
	'author' => $this->theme->get('Author'),
	'author_uri' => $this->theme->get('AuthorURI')
];
```

## Impact
This code does no harm things or have great impact on the core. It just simply get more data from `wp_get_theme()`. Totally safe.

## Usage Changes
See **Solution**, that's all I got.

## Considerations
Please check my issue:  https://github.com/timber/timber/issues/2049

## Testing
Not yet... I don't even know how to do that :p

### CODE REVIEW

**Comment by dtvn** [comment]
This is the first time I ever work in git stuff. Tried to understand how the pull work but I still a bit trouble. Very sorry if it troubles everyone.

**Comment by gchtr** [comment]
> This is the first time I ever work in git stuff. Tried to understand how the pull work but I still a bit trouble. Very sorry if it troubles everyone.

No worries! Thank you for taking the time to sit down and make your first pull request! I know, it can be confusing first, but we’ve all been there 😉. Usually, you would want to make a pull request against the `master` branch, so you have to select `master` as the base. I already changed that for you. Now it looks a bit cleaner.

I think making all the theme info accessible is a good idea! But I wouldn’t go with the name `$meta`, because in Timber, we reserve "meta" for everything that’s save in a meta database table.

And I wonder if we would need to load in all the data, or if we want to only make the `get()` and the `display()` functions accessible:

```php
namespace Timber;

class Theme extends Core {
    /**
     * Gets a raw, unformatted theme header.
     * 
     * @api 
     * @see \WP_Theme::get()
     * @example
     * ```twig
     * {{ theme.get('Version') }}
     * ```
     *
     * @param string $header Name of the theme header. Name, Description, Author, Version,
     *                       ThemeURI, AuthorURI, Status, Tags.
     *
     * @return false|string String on success, false on failure.
     */
    public function get( $header ) {
        return $this->theme->get( $header );
    }

    /**
     * Gets a theme header, formatted and translated for display.
     *
     * @api
     * @see \WP_Theme::display()
     * @example
     * ```twig
     * {{ theme.display('Description') }}
     * ```
     *
     * @param string $header Name of the theme header. Name, Description, Author, Version,
     *                       ThemeURI, AuthorURI, Status, Tags.
     *
     * @return false|string
     */
    public function display( $header ) {
        return $this->theme->display( $header );
    }
}
```

This way, we don’t have to duplicate all the available headers into the Timber class. What do you think?

**Comment by dtvn** [comment]
Ok, sorry, I didn't search carefully enough. Just found out the `meta` keywords also has something to do with `Timber\Core` method. I'll take note this and leave an image here to remind myself:

image

And I totally agree with your code. It would increase process time and saving some memory space for server. So, should I rewrite the source and make a request again?

**Comment by jarednova** [comment]
Thanks @dtvn! I added tests and notes to the readme in #2065 and just merged them in. This will be in the next release of Timber!

I really hope you'll keep contributing PRs like this. These tests were pretty easy to write, here's the full info on including tests from our docs: https://timber.github.io/docs/guides/testing/

**Pull request merged**
