### PR TITLE
Fix get_post_preview_id for custom post types that use capability_type

### PR DESCRIPTION
**Pull request by BernsteinA**
**Ticket**: #375 (builds on PR #876)

#### Issue
If a custom post type is registered and sets `capability_type`, the current code does not correctly resolve permissions for the purposes of previewing changes to an already published post.
For example, I have a custom post type of `article`, but with `capability_type`=>`page`:
`'edit_' . $query->queried_object->post_type . 's',` resolves to `edit_articles`, rather than the correct `edit_page`.

#### Solution
Use `get_post_type_object`->`cap` to get the actual name of the capability

#### Impact
This should not break anything for anyone

#### Usage Changes
None

#### Considerations
`get_post_type_object($query->queried_object->post_type)` feels a bit clunky

#### Testing
Needs test?

### CODE REVIEW

**Comment by jarednova** [comment]
Hi @BernsteinA — thanks for the PR! Fixing these diff't use cases is really important so Timber keeps getting more reliable. Unfortunatley it looks like the changes are erroring-out for two tests:

```
1) TestTimberPost::testPreviewContent
Undefined offset: 0
/tmp/wordpress/wp-includes/capabilities.php:122
/tmp/wordpress/wp-includes/class-wp-user.php:723
/tmp/wordpress/wp-includes/capabilities.php:530
/home/travis/build/timber/timber/lib/Post.php:277
/home/travis/build/timber/timber/lib/Post.php:228
/home/travis/build/timber/timber/lib/Post.php:181
/home/travis/build/timber/timber/tests/test-timber-post.php:297
2) TestTimberPost::testMultiPreviewRevisions
Undefined offset: 0
/tmp/wordpress/wp-includes/capabilities.php:122
/tmp/wordpress/wp-includes/class-wp-user.php:723
/tmp/wordpress/wp-includes/capabilities.php:530
/home/travis/build/timber/timber/lib/Post.php:277
/home/travis/build/timber/timber/lib/Post.php:228
/home/travis/build/timber/timber/lib/Post.php:181
/home/travis/build/timber/timber/tests/test-timber-post.php:335
```

Can you take a look at those and see if you can figure out what's going on or needs to be changed?

**Comment by BernsteinA** [comment]
@jarednova I'm on it. Can you point me to documentation on how to run the tests locally?

**Comment by jarednova** [comment]
You bet! https://timber.github.io/docs/guides/testing/

**Comment by jarednova** [comment]
Brilliant, thanks @BernsteinA !

**Pull request merged**
