### PR TITLE
Adding get term

### PR DESCRIPTION
**Pull request by connorjburton**
**Ticket**: #386 
**Reviewer**: @jarednova @ste93cry

#### Issue

There was no wrapper for `get_term`

#### Solution

Adds wrapper

#### Impact

None

#### Usage

`Timber::get_term(params)`

#### Considerations

This needs testing, I literally just added a wrapper, `get_terms` seems to do a lot more.

#### Testing

Needs a test

### CODE REVIEW

**Comment by jarednova** [comment]
Hey @connorjburton: thanks for submitting! Here's my only thought on tweak....

While it makes sense to mirror WP's argument order (which in this case is... `($term, $taxonomy, $output, $filter)`) the last two (`$output` and `$filter`) seem not particularly useful — or at least _less_ useful than `$TermClass`; what are your thoughts on tweaking this to be: 

`$term, $taxonomy, $TermClass, $output, $filter` ?

**Comment by connorjburton** [comment]
Gotcha, will resolve

**Comment by ste93cry** [comment]
Does it makes sense to have `$output` an `$filter`? The first according to the WordPress [documentation](https://codex.wordpress.org/Function_Reference/get_term) should tweak the type of the result (which is not needed in our case because we're going anywhere to wrap it with `TimberTerm`) while the second should filter how the data is filtered (what's the purpose of it in our function?)

**Comment by connorjburton** [comment]
Remove the un-necessary args

**Comment by jarednova** [comment]
Thanks @connorjburton! Just added a quick test – we're good to go!

**Pull request merged**
