### PR TITLE
Improve notes about CDN limitations

### PR DESCRIPTION
**Pull request by gchtr**
**Ticket**: #1925

Let’s rewrite the CDN limitation section again based on the new information provided by @palmiak. It looks like when Maciej talked about «Push CDN», he was talking about the same as the following section by Jared:

> However, there may be some CDN setups that work fine with the above filters (for example: one that’s merely watching the contents of the `wp-content/uploads` directory and copying it to the CDN). For example, the filters seem to work fine with the default setups for WPEngine and Pantheon.

I changed the text to first hint about the differences between Push and Pull CDN and then describe how this relates to Timber.

### CODE REVIEW

**Comment by gchtr** [comment]
@jarednova Cool, yeah, additional headings surely help! I just added them.

However, from looking at #1929, there are also issues when working with WPEngine, which you mentioned should work. I’m guessing this needs yet another round of clarifications. Do we have any knowledge about CDN plugins that work flawlessly?

**Comment by palmiak** [comment]
@gchtr I only used W3Total Cache with maxCDN (which is a typical pull zone). I don't know anything about those hosting related CDNs (like WPEngine) we would need to test them one by one.

**Comment by jarednova** [comment]
Yeah, this info is definitely an improvement. A good @todo to come out of it would be to take a few popular WP hosts and describe their current compatibility. Even if it's a limited list, it might encourage others (or who knows, the hosts themselves?) to state where they are

**Comment by gchtr** [comment]
Cool! I will start a new issue with a basic table of what we currently now.

**Pull request merged**
