### PR TITLE
2.x Drop support for PHP versions < 5.x

### PR DESCRIPTION
**Pull request by gchtr**
**Ticket: #1965**

When we drop support for Twig 1.x in #1965, we will have to drop support for PHP 5.x. The [Travis log says it](https://travis-ci.org/timber/timber/jobs/534011840):

```
twig/twig v2.9.0 requires php ^7.0 -> your PHP version (5.6.30) does not satisfy that requirement.
```

I added this pull request to handle this separately. We already discussed this a bit in #1863. WordPress updated the [minimum required PHP version to 5.6](https://make.wordpress.org/core/2018/12/08/updating-the-minimum-php-version/). WordPress has to consider a lot more backwards compatibility and consider setups that are a little more low-level than Timber. I think we can introduce a minimum PHP version of 7.0 for Timber.

## Solution

This pull request updates the Composer requirements, the Travis file and the Upgrade guide.

## Impact

Timber can only be installed in environments that support PHP 7.x.

## Usage Changes

No.

## Considerations

I’m asking myself, should we go even higher and make 7.2 the minimum required version? When we look at the [Supported Versions of PHP](https://secure.php.net/supported-versions.php), PHP 7.0 has already reached End of Life and active support for PHP 7.1 has already ended by the end of 2018.

However, I have no idea about the hosting landscape out there that Timber developers use and whether a version 7.2 would be too high. Is 7.2 already widely available on hosters? Should we use a minimum required version of 7.2 to nudge everyone into a modern stack?

What are your thoughts on this (@jarednova @acobster @pascalknecht @palmiak @chrisvanpatten)? Or anyone else who wants to chime in?

## Testing

Let Travis do the testing and see what comes up.

### CODE REVIEW

**Comment by jarednova** [comment]
@gchtr nice to not have to worry about PHP 5 in 2.x anymore. God, that will make the tests go faster. In terms of PHP 7.0 vs. 7.2, I think we should be aware of what WP.org stats have for us there:

https://wordpress.org/about/stats/

... currently PHP 7.x is found on about 50% of installs — PHP 7.2+ is on about 20% of installs. Obviously, this number is only going to increase. My vote is to bite the bullet and go 7.2. I think the developers who are likely to use Timber 2 aren't going to be on a $5 GoDaddy server. 

WPEngine (which I consider a good barometer of a WP host here in 🇺🇸 ) is pushing customers to upgrade to 7.2. This trend is only going to continue.

**Comment by gchtr** [comment]
> WPEngine (which I consider a good barometer of a WP host here in 🇺🇸 ) is pushing customers to upgrade to 7.2. This trend is only going to continue.

It’s the same here in Switzerland 🇨🇭. PHP 5.6 is not available anymore, and PHP 7.2 is the new standard.

**Comment by chrisgherbert** [comment]
Requiring 7.2 feels like a step too far. While we’d all love to use hosts that stay on the cutting edge, clients don’t always make that a priority.

**Comment by acobster** [comment]
I agree, we should shoot for parity with Twig.

**Comment by jarednova** [comment]
"parity with Twig" feels like the perfect place to leave this: easy to explain/justify and maintain over time

**Comment by gchtr** [comment]
Thank you all for your answers! 👍 We’re sure in no rush to update to 7.2. And parity with Twig indeed seems like a very good approach. Let’s do that!

**Pull request merged**
