### PR TITLE
Eliminate Recursion in Menu / MenuItem

### PR DESCRIPTION
**Pull request by jarednova**
**Ticket**: #2071 

## Issue
There's recursion in a Menu's MenuItem's Menus

## Solution
Convert the public `MenuItem::$menu` property into a public method

## Impact
This will break any PHP-based calls to `MenuItem::$menu` however, anything in Twig should still work (since it will pass the call of `{{ menuitem.menu }}` off to the method)

## Usage Changes
In PHP, to get a MenuItem's menu, the dev should use:
```php
$menu = $menu_item->menu();
```

## Considerations
Would be great to make calls to the `$menu` property backwards compatible

## Testing
New test to validate no recursion; might need additional test to cover new method

### CODE REVIEW

**Comment by jarednova** [comment]
Travis tests are still failing (though they pass on my local); please hold off on any review/merge until I can resolve

**Comment by jarednova** [comment]
Looks like those failing tests are now resolved (good thing they failed, helped me to identify a bug that this created related to a `MenuItem`'s depth!). Would love another set of 👀  on this ...

**Comment by jarednova** [comment]
@gchtr thanks for your feedback, back to you! Just a few tweaks were needed to take care of those items

**Comment by gchtr** [comment]
@jarednova Thanks for the changes!

> Instead, could we add a deprecation call to a `__get()` method, that checks if the protected `$menu` property is accessed?

I’m assuming you don’t want to catch direct calls to `MenuItem::$menu` then?

**Comment by jarednova** [comment]
@gchtr actually, it turns out we get that already w/o any modification to `__get()` ....

I wrote this test to validate (which passes):

```php
function testMenuItemMenuProperty() {
		$pg_1 = $this->factory->post->create( array( 'post_type' => 'page', 'post_title' => 'Foo Page', 'menu_order' => 10 ) );
		$pg_2 = $this->factory->post->create( array( 'post_type' => 'page', 'post_title' => 'Bar Page', 'menu_order' => 1 ) );
		$page_menu = new Timber\Menu();
		$items = $page_menu->get_items();
		$menu = $items[0]->menu;
		$this->assertEquals('Timber\Menu', get_class($menu));
	}
```

... the logic in `__get()` looks for methods with that name and already uses them instead of properties.

**Comment by gchtr** [comment]
@jarednova Oh, I see! Very well then. Let’s merge this in!

**Pull request merged**
