### PR TITLE
Make Coveralls merge our 3 coverage reports

### LINKED ISSUE #2288: Consequent coverage reports *overwrite* each other
From #2286 

```yaml
    - php: 7.4
      env: WP_VERSION=latest WP_MULTISITE=0 IMG_LIBS=1 COVERAGE=1
    - php: 7.4
      env: WP_VERSION=latest WP_MULTISITE=1 IMG_LIBS=0 COVERAGE=1
```

Currently we upload coverage data to Coveralls then we **overwrite** it with multisite coverage data.

What to do now??

### PR DESCRIPTION
**Pull request by szepeviktor**
Fixes #2288

🙊 

> When your CI is building in parallel, you’ll want your coverage results to be merged after all have completed.

### CODE REVIEW

**Comment by szepeviktor** [comment]
and separate PHP 5.6 job in CI

**Comment by szepeviktor** [comment]
Meanwhile discovered that Composer is loosing its cache between CI jobs.

**Comment by szepeviktor** [comment]
> There was 1 error:
> 
> 1) TestTimberPost::testPostWithVideo
> 
> PHPUnit\Framework\Exception: Argument #2 (No Value) of PHPUnit\Framework\Assert::assertRegExp() must be a string
> 
> /home/travis/build/timber/timber/tests/test-timber-post.php:981

Why now??? :)

**Comment by szepeviktor** [comment]
Travis status says

> AWS ec2-us-east-1 -> Degraded Performance

Yes! Everyone go @UpCloud!

**Comment by szepeviktor** [comment]
@jarednova Did you know that we have a PHP 5.6 coverage uploaded too?

**Comment by szepeviktor** [comment]
Next step: remove `$COVERAGE` from CI config

**Comment by jarednova** [comment]
Looking good @szepeviktor — thanks for cleaning these up! Once we remove PHP 5.6 that'll further smooth out the testing script

**Comment by szepeviktor** [comment]
You're welcome.

**Pull request merged**
