### PR TITLE
Make Timber_Theme use the native WP_Theme class

### PR DESCRIPTION
**Pull request by xavivars**
**Ticket**: #1280 1280
**Reviewer**: @ 

#### Issue
Timber\Theme was (incorrectly) reimplenting some logic already existing in WP_Theme

#### Solution
* Make Timber\Theme a thin wrapper on top of WP_Theme
* Use WP Theme test setup

#### Impact
Small

#### Usage
Transparent for all users

#### Testing
All existing tests are passing.

### CODE REVIEW

**Comment by jarednova** [comment]
@xavivars looking good! Travis caught a few failing tests though...

- `TestTimberSite::testChildParentThemeLocation`
- `TestTimberTwig::testTranslate`
- `TestTimberTwig::testTranslateAndFormat`


... any ideas on those guys?

**Comment by xavivars** [comment]
The problem with the `TestTimberTwig` tests was that the tests were not really "unit": they were depending on other setup tasks. When executed in isolation, they were working, but they were failing when executing all the suite.

I changed the `mkdir` to be recursive, and I've also fixed the teardown I added to the `TestTimberTheme` and they're passing now.

I'll try to dig into the `TestTimberSite` one, but I could not reproduce the issue locally.

**Comment by xavivars** [comment]
@jarednova I still can't reproduce `TestTimberSite`'s issue locally. It'd be great if you could take a look at it, as I don't know what else to try...

**Comment by jarednova** [comment]
@xavivars sure thing! thanks for getting 2/3rds of 'em taken care of

**Comment by xavivars** [comment]
@jarednova I think there are still tests that do not do proper tearDown: when I deleted all tmp wordpress files, I managed to reproduce.

That said, I think I finally solved it :)

**Comment by jarednova** [comment]
Awesome, thanks for closing that out @xavivars. Merging!

**Pull request merged**
