### PR TITLE
URLHelper::get_params() return value

### PR DESCRIPTION
**Pull request by acobster**
PHPStan considers implicit null returns a bug:

```
 ------ ---------------------------------------------------------------------------------------------------                                                                                                        
  Line   URLHelper.php                                                                                                                                                                                             
 ------ ---------------------------------------------------------------------------------------------------                                                                                                        
  533    Method Timber\URLHelper::get_params() should return array|string but return statement is missing.                                                                                                         
 ------ --------------------------------------------------------------------------------------------------- 
```

The fix is to always explicitly return, as well as declare the right `@return` type. I did some cleanup for conciseness, too.

No usage changes or other considerations I'm aware of. Tests still pass.

### CODE REVIEW

**Comment by jarednova** [comment]
Much cleaner! Just changed `false` => `null` in the function description to match

**Review by jarednova — DISMISSED** [review]

**Review by jarednova — APPROVED** [review]

**Comment by acobster** [comment]
whoops! Yeah I had thought to make it `false` to make it a little more consistent with other core functions, but `null` is more appropriate if you're thinking of it as an array. Still on the fence about this though. Thoughts?

**Comment by jarednova** [comment]
Oh roger, that I thought you had settled on `null` based on the code. I think this is one of those 51/49 situations, but `false` would seem to be the more expected value returned (you could imagine using `get_params()` in conditionals — and I'm never confident about how `null` behaves in those situations)

**Comment by acobster** [comment]
OK, I'll change it to `false` then. Bringing it up because it's _technically_ a breaking change, although it'll only break code that's checking `null === URLHelper::get_params(...)` which seems pretty unlikely and edge-casey.

**Comment by acobster** [comment]
OK @jarednova - done. If you could give another once-over that'd be great.

**Comment by jarednova** [comment]
Once-overed! Looks good from here

**Pull request merged**
