### PR TITLE
WIP: Feature/interfaced object factories

### PR DESCRIPTION
**Pull request by pascalknecht**
Merge of #1220. Feature will be developed further here.

### CODE REVIEW

**Comment by pascalknecht** [comment]
Current todo

- [ ] Fix tests
- [ ] Write new tests for the factory
- [ ] Document API
- [ ] Document Filters
- [ ] Adjust Timber Functions (Post, Image, etc.)

**Comment by acobster** [comment]
@gchtr thanks for the heads up, moving discussion over here. I wanted to reply directly to some of your ideas in your [comment](https://github.com/timber/timber/pull/1219#issuecomment-441321320):

> I’ve found the Timber\PostClassMap filter, which is currently named timber/post/post_class in 2.x to be quite a useful pattern

Yeah, a fully fledged custom Factory class might be overkill sometimes, and this filter would serve users well for those cases. Implementing and injecting your own Factory class should probably short-circuit the, as having both a custom `MyPostFactory` and the `timber/post/post_class` in operation could be confusing.

> I’m still thinking about a proper API. Should we keep the existing functions...Or should we use something that might be a little easier to read?
> 
> * `Post::get()`
> * ...

See my comment above. I'm not married to keeping the `Timber::get_*` convenience methods but I do think it is the most flexible because it doesn't lock you down to a specific factory class.

**Comment by gchtr** [comment]
> Yeah, a fully fledged custom Factory class might be overkill sometimes, and this filter would serve users well for those cases. Implementing and injecting your own Factory class should probably short-circuit the, as having both a custom `MyPostFactory` and the `timber/post/post_class` in operation could be confusing.

I agree.

> See my comment above. I'm not married to keeping the `Timber::get_*` convenience methods but I do think it is the most flexible because it doesn't lock you down to a specific factory class.

True that. I figured `Timber::get_post()` is also closer to what we are used in WordPress, where we have `get_post()`.

**Comment by pascalknecht** [comment]
@acobster So let's get on the drawing board here 👍 

I would prefer having seperate classes for the object factories as this is more clean. I kinda like the `Post::get()` syntax. What I currently don't like is the fact that this implementation is stateful as we would need to access the global queried object. This should in my opinion not be necessary. I would prefer to create the implementation stateless and keep all state in the calling code.

Example:
``` php
// single.php or page.php
$context = Timber::get_context();
$context['post'] = Post::get(get_queried_object()->ID);
```
The same thing would be needed for term pages
``` php
// taxonomy.php
$context = Timber::get_context();
$context['term'] = Term::get(get_queried_object()->ID);
```
When the id is undefined a null object or null should be returned. I don't like when it returns a fully fledged object if the post is not found.

Then we will think about the implementation of the filters. I will need to think about this further.
Furthermore I would really like to have the possibility of having a class that everytime maps to a certain post type.

**Comment by acobster** [comment]
@pascalknecht sounds good.

> I would prefer having seperate classes for the object factories as this is more clean. I kinda like the Post::get() syntax.

Fine with me, as long as we're not locking calling code in to a specific factory class. :) That syntax looks nice to me.

> I would prefer to create the implementation stateless and keep all state in the calling code.

Yes, relying on global state in library code scares me too. Let's get rid of it!

> Furthermore I would really like to have the possibility of having a class that everytime maps to a certain post type.

Could you say more about this? Not sure what you mean.

**Comment by pascalknecht** [comment]
@gchtr Yes exactly. So we will have the best of both worlds: Stateless factories and easy implementation.

> Furthermore I would really like to have the possibility of having a class that everytime maps to a certain post type.
> 
> Could you say more about this? Not sure what you mean.

@acobster The factory should be able to map certain post types to a specific subclass of `TimberPost`. For example if i have a post type `event` I would like to be able to add a class `Event` and have it automatically loaded for this post type. That's a feature which I think was already possible but not as nice to use.

**Comment by pascalknecht** [comment]
@gchtr @acobster @jarednova Do we all agree on this new API or do you have any inputs/objections/improvements?

**Comment by gchtr** [comment]
I agree! No objections so far.

**Comment by acobster** [comment]
@pascalknecht ah ok, so specifically it's mapping `post_type` to a class name, essentially?

**Comment by pascalknecht** [comment]
@gchtr @acobster  I created a first test implementation here: https://github.com/timber/timber/tree/new_object_factory . I was able to get rid of the PostClass String as we can now use polymorphism for this. Not yet sure whether we should use a seperate class for the Factory. We will probably also be able to get rid of all hardcoded class names with the factories,

**Comment by pascalknecht** [comment]
@acobster Agreed. I added this with a minor change as you forgot to add the instantiation of the class in your code sample above. Do you think we should remove the constructor all together and keep everything in the static `get` function? Should I overwrite this PR or would it be better to open a new PR?

**Comment by acobster** [comment]
@pascalknecht this is shaping up!

>  I added this with a minor change as you forgot to add the instantiation of the class in your code sample above

whoops! Oh well, minor details ;)

> Do you think we should remove the constructor all together and keep everything in the static `get` function?

Do you mean remove the constructor from the `Post` (and presumably other `Core` classes?) class itself, letting it fall back to `stdclass` or whatever? I'm not sure. I guess `__construct` doesn't need to take any arguments now, and if people really want to bootstrap some internal state they still can. So, I don't really see any reason to keep the default constructor around...is that your thinking?

My only other concern is with initializing the post data, since that would no longer happen inside the constructor. Are you thinking that we'd hook into `timber/post/instance` by default to call `import()`? I think that'd be a nice, decoupled way to do it, since it allows turning off the data-import step if necessary. But if so, we'll want to pass `$query_object` to that hook.

> Should I overwrite this PR or would it be better to open a new PR?

I'm leaning towards a new PR since the code is so different. But I'll leave that up to you.

**Comment by gchtr** [comment]
@pascalknecht @acobster Just checking in to see what the status is here. Do you have everything you need to keep working on this?

**Comment by acobster** [comment]
@gchtr everything except time. Agency life! :laughing: :sob: 

@pascalknecht I can try to wrap this one up since I feel like I have a pretty solid handle on what needs to happen from here, but I probably won't be able to make progress for another couple weeks. Would love to at least get your thoughts on my last few questions just to make sure we're on the same page. Thanks!

**Comment by pascalknecht** [comment]
@acobster Yes that would be great. I can help out where needed but currently don't have the time to do it alone. Let's discuss everthing here so that we are working towards the same goals.

**Comment by pascalknecht** [comment]
@acobster Sorry cannot find the questions. Where were those?

**Comment by acobster** [comment]
@pascalknecht  I guess GitHub decided to hide most of our discussion. The questions I was referring to are in [this comment](https://github.com/timber/timber/pull/1793#issuecomment-462406397).

**Comment by acobster** [comment]
@gchtr @jarednova @pascalknecht so I've been able to make some incremental progress in porting more tests over to the new `Timber\Post::get()` syntax...however, I'm running into quite a few test failures on this branch, and on the `2.x` branch the tests won't even run:

```
vagrant@vvv:/vagrant/www/timber$ git branch
* 2.x
  feature/interfaced-object-factories
  master
vagrant@vvv:/vagrant/www/timber$ phpunit
Installing...
Running as single site... To run multisite, use -c tests/phpunit/multisite.xml
PHP Fatal error:  Cannot redeclare Timber\Timber::$version in /vagrant/www/timber/lib/Timber.php on line 44

Fatal error: Cannot redeclare Timber\Timber::$version in /vagrant/www/timber/lib/Timber.php on line 44
PHP Warning:  Use of undefined constant RECOVERY_MODE_COOKIE - assumed 'RECOVERY_MODE_COOKIE' (this will throw an Error in a future version of PHP) in /vagrant/www/wordpress-trunk/public_html/src/wp-includes/class-wp-recovery-mode-cookie-service.php on line 66

Warning: Use of undefined constant RECOVERY_MODE_COOKIE - assumed 'RECOVERY_MODE_COOKIE' (this will throw an Error in a future version of PHP) in /vagrant/www/wordpress-trunk/public_html/src/wp-includes/class-wp-recovery-mode-cookie-service.php on line 66
PHP Warning:  Use of undefined constant COOKIE_DOMAIN - assumed 'COOKIE_DOMAIN' (this will throw an Error in a future version of PHP) in /vagrant/www/wordpress-trunk/public_html/src/wp-includes/class-wp-recovery-mode-cookie-service.php on line 67

Warning: Use of undefined constant COOKIE_DOMAIN - assumed 'COOKIE_DOMAIN' (this will throw an Error in a future version of PHP) in /vagrant/www/wordpress-trunk/public_html/src/wp-includes/class-wp-recovery-mode-cookie-service.php on line 67
PHP Warning:  Use of undefined constant COOKIEPATH - assumed 'COOKIEPATH' (this will throw an Error in a future version of PHP) in /vagrant/www/wordpress-trunk/public_html/src/wp-includes/class-wp-recovery-mode-cookie-service.php on line 68

Warning: Use of undefined constant COOKIEPATH - assumed 'COOKIEPATH' (this will throw an Error in a future version of PHP) in /vagrant/www/wordpress-trunk/public_html/src/wp-includes/class-wp-recovery-mode-cookie-service.php on line 68
PHP Warning:  Use of undefined constant SITECOOKIEPATH - assumed 'SITECOOKIEPATH' (this will throw an Error in a future version of PHP) in /vagrant/www/wordpress-trunk/public_html/src/wp-includes/class-wp-recovery-mode-cookie-service.php on line 69

Warning: Use of undefined constant SITECOOKIEPATH - assumed 'SITECOOKIEPATH' (this will throw an Error in a future version of PHP) in /vagrant/www/wordpress-trunk/public_html/src/wp-includes/class-wp-recovery-mode-cookie-service.php on line 69
```

I'm wondering if I'm missing some setup or something. This is a fairly fresh install of VVV using the [standard Timber testing setup](https://timber.github.io/docs/guides/testing/).

**Comment by jarednova** [comment]
hmmmm @acobster — have to admit those errors aren't ones I've encountered before, what happens if you run against `master`?

This line seems interesting:

```PHP Fatal error:  Cannot redeclare Timber\Timber::$version in /vagrant/www/timber/lib/Timber.php on line 44```

— it seems to indicate there's already an instance of Timber loaded in the install you're running

**Comment by acobster** [comment]
@jarednova yeah, I thought that was especially weird as well.

Here's the output on `master` (excluding the handful of lines that print to `stderr`):

```
Installing...
Running as single site... To run multisite, use -c tests/phpunit/multisite.xml
Not running ajax tests. To execute these, use --group ajax.
Not running ms-files tests. To execute these, use --group ms-files.
Not running external-http tests. To execute these, use --group external-http.
PHPUnit 6.5.14 by Sebastian Bergmann and contributors.

Error:         No code coverage driver is available

.....R...................................R.....................  63 / 706 (  8%)
.........................SSS..........................E..E..... 126 / 706 ( 17%)
...................................SS.......................... 189 / 706 ( 26%)
.........................................................S..... 252 / 706 ( 35%)
........F......F....................................SS......... 315 / 706 ( 44%)
...R..................R............R.............REE........... 378 / 706 ( 53%)
............................................................... 441 / 706 ( 62%)
.....R.............................................F......EEEEF 504 / 706 ( 71%)
EEEEEEEEEEEE..............................................F.... 567 / 706 ( 80%)
...........RR.................................................. 630 / 706 ( 89%)
..........................................RR................... 693 / 706 ( 98%)
.............                                                   706 / 706 (100%)

Time: 2.87 minutes, Memory: 48.25MB

There were 20 errors:

1) TestTimberHelper::testCommentFormPHP
Trying to get property 'post_type' of non-object

/vagrant/www/timber/wp-content/plugins/advanced-custom-fields/includes/forms/form-comment.php:226
/vagrant/www/wordpress-trunk/public_html/src/wp-includes/class-wp-hook.php:286
/vagrant/www/wordpress-trunk/public_html/src/wp-includes/plugin.php:208
/vagrant/www/wordpress-trunk/public_html/src/wp-includes/comment-template.php:2464
/vagrant/www/timber/lib/Helper.php:168
/vagrant/www/timber/lib/Helper.php:459
/vagrant/www/timber/tests/test-timber-helper.php:48
/vagrant/www/timber/vendor/phpunit/phpunit/src/Framework/TestResult.php:698
/vagrant/www/timber/vendor/phpunit/phpunit/src/TextUI/TestRunner.php:545

2) TestTimberHelper::testCommentForm
Trying to get property 'post_type' of non-object

/vagrant/www/timber/wp-content/plugins/advanced-custom-fields/includes/forms/form-comment.php:226
/vagrant/www/wordpress-trunk/public_html/src/wp-includes/class-wp-hook.php:286
/vagrant/www/wordpress-trunk/public_html/src/wp-includes/plugin.php:208
/vagrant/www/wordpress-trunk/public_html/src/wp-includes/comment-template.php:2464
/vagrant/www/timber/lib/Helper.php:168
/vagrant/www/timber/tests/test-timber-helper.php:67
/vagrant/www/timber/vendor/phpunit/phpunit/src/Framework/TestResult.php:698
/vagrant/www/timber/vendor/phpunit/phpunit/src/TextUI/TestRunner.php:545

3) TestTimberPostGetter::testGettingEmptyArray
count(): Parameter must be an array or an object that implements Countable

/vagrant/www/timber/tests/test-timber-post-getter.php:156
/vagrant/www/timber/vendor/phpunit/phpunit/src/Framework/TestResult.php:698
/vagrant/www/timber/vendor/phpunit/phpunit/src/TextUI/TestRunner.php:545

4) TestTimberPostGetter::testGettingWithFalse
count(): Parameter must be an array or an object that implements Countable

/vagrant/www/timber/tests/test-timber-post-getter.php:162
/vagrant/www/timber/vendor/phpunit/phpunit/src/Framework/TestResult.php:698
/vagrant/www/timber/vendor/phpunit/phpunit/src/TextUI/TestRunner.php:545

5) TestTimberRouter::testThemeRoute
Error: Class 'Routes' not found

/vagrant/www/timber/tests/test-timber-router.php:6
/vagrant/www/timber/vendor/phpunit/phpunit/src/Framework/TestResult.php:698
/vagrant/www/timber/vendor/phpunit/phpunit/src/TextUI/TestRunner.php:545

6) TestTimberRouter::testThemeRouteDoesntExist
Error: Class 'Routes' not found

/vagrant/www/timber/tests/test-timber-router.php:16
/vagrant/www/timber/vendor/phpunit/phpunit/src/Framework/TestResult.php:698
/vagrant/www/timber/vendor/phpunit/phpunit/src/TextUI/TestRunner.php:545

7) TestTimberRouter::testFullPathRoute
Error: Class 'Routes' not found

/vagrant/www/timber/tests/test-timber-router.php:22
/vagrant/www/timber/vendor/phpunit/phpunit/src/Framework/TestResult.php:698
/vagrant/www/timber/vendor/phpunit/phpunit/src/TextUI/TestRunner.php:545

8) TestTimberRouter::testFullPathRouteDoesntExist
Error: Class 'Routes' not found

/vagrant/www/timber/tests/test-timber-router.php:28
/vagrant/www/timber/vendor/phpunit/phpunit/src/Framework/TestResult.php:698
/vagrant/www/timber/vendor/phpunit/phpunit/src/TextUI/TestRunner.php:545

9) TestTimberRouter::testAppliedRoute
Error: Class 'Routes' not found

/vagrant/www/timber/tests/test-timber-router.php:41
/vagrant/www/timber/vendor/phpunit/phpunit/src/Framework/TestResult.php:698
/vagrant/www/timber/vendor/phpunit/phpunit/src/TextUI/TestRunner.php:545

10) TestTimberRouter::testRouteAgainstPostName
Error: Class 'Routes' not found

/vagrant/www/timber/tests/test-timber-router.php:57
/vagrant/www/timber/vendor/phpunit/phpunit/src/Framework/TestResult.php:698
/vagrant/www/timber/vendor/phpunit/phpunit/src/TextUI/TestRunner.php:545

11) TestTimberRouter::testFailedRoute
Error: Class 'Routes' not found

/vagrant/www/timber/tests/test-timber-router.php:72
/vagrant/www/timber/vendor/phpunit/phpunit/src/Framework/TestResult.php:698
/vagrant/www/timber/vendor/phpunit/phpunit/src/TextUI/TestRunner.php:545

12) TestTimberRouter::testRouteWithVariable
Error: Class 'Routes' not found

/vagrant/www/timber/tests/test-timber-router.php:87
/vagrant/www/timber/vendor/phpunit/phpunit/src/Framework/TestResult.php:698
/vagrant/www/timber/vendor/phpunit/phpunit/src/TextUI/TestRunner.php:545

13) TestTimberRouter::testRouteWithAltoVariable
Error: Class 'Routes' not found

/vagrant/www/timber/tests/test-timber-router.php:105
/vagrant/www/timber/vendor/phpunit/phpunit/src/Framework/TestResult.php:698
/vagrant/www/timber/vendor/phpunit/phpunit/src/TextUI/TestRunner.php:545

14) TestTimberRouter::testRouteWithMultiArguments
Error: Class 'Routes' not found

/vagrant/www/timber/tests/test-timber-router.php:119
/vagrant/www/timber/vendor/phpunit/phpunit/src/Framework/TestResult.php:698
/vagrant/www/timber/vendor/phpunit/phpunit/src/TextUI/TestRunner.php:545

15) TestTimberRouter::testRouteWithMultiArgumentsOldStyle
Error: Class 'Routes' not found

/vagrant/www/timber/tests/test-timber-router.php:138
/vagrant/www/timber/vendor/phpunit/phpunit/src/Framework/TestResult.php:698
/vagrant/www/timber/vendor/phpunit/phpunit/src/TextUI/TestRunner.php:545

16) TestTimberRouter::testVerySimpleRoute
Error: Class 'Routes' not found

/vagrant/www/timber/tests/test-timber-router.php:158
/vagrant/www/timber/vendor/phpunit/phpunit/src/Framework/TestResult.php:698
/vagrant/www/timber/vendor/phpunit/phpunit/src/TextUI/TestRunner.php:545

17) TestTimberRouter::testVerySimpleRouteTrailingSlash
Error: Class 'Routes' not found

/vagrant/www/timber/tests/test-timber-router.php:173
/vagrant/www/timber/vendor/phpunit/phpunit/src/Framework/TestResult.php:698
/vagrant/www/timber/vendor/phpunit/phpunit/src/TextUI/TestRunner.php:545

18) TestTimberRouter::testVerySimpleRouteTrailingSlashInRequest
Error: Class 'Routes' not found

/vagrant/www/timber/tests/test-timber-router.php:188
/vagrant/www/timber/vendor/phpunit/phpunit/src/Framework/TestResult.php:698
/vagrant/www/timber/vendor/phpunit/phpunit/src/TextUI/TestRunner.php:545

19) TestTimberRouter::testVerySimpleRouteTrailingSlashInRequestAndMapping
Error: Class 'Routes' not found

/vagrant/www/timber/tests/test-timber-router.php:204
/vagrant/www/timber/vendor/phpunit/phpunit/src/Framework/TestResult.php:698
/vagrant/www/timber/vendor/phpunit/phpunit/src/TextUI/TestRunner.php:545

20) TestTimberRouter::testVerySimpleRoutePreceedingSlash
Error: Class 'Routes' not found

/vagrant/www/timber/tests/test-timber-router.php:219
/vagrant/www/timber/vendor/phpunit/phpunit/src/Framework/TestResult.php:698
/vagrant/www/timber/vendor/phpunit/phpunit/src/TextUI/TestRunner.php:545

--

There were 5 failures:

1) TestTimberIntegrations::testACFFieldObject
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'foo / field_thinger'
+'foo / '

/vagrant/www/timber/vendor/phpunit/phpunit/src/Framework/Constraint/IsEqual.php:136
/vagrant/www/timber/tests/test-timber-integrations.php:83
/vagrant/www/timber/vendor/phpunit/phpunit/src/Framework/TestResult.php:698
/vagrant/www/timber/vendor/phpunit/phpunit/src/TextUI/TestRunner.php:545

2) TestTimberIterator::testTheLoop
Failed asserting that 'TestPost1\n
    TestPost2' starts with "TestPost2".

/vagrant/www/timber/vendor/phpunit/phpunit/src/Framework/Constraint/Constraint.php:117
/vagrant/www/timber/vendor/phpunit/phpunit/src/Framework/Constraint/Constraint.php:62
/vagrant/www/timber/tests/test-timber-iterator.php:22
/vagrant/www/timber/vendor/phpunit/phpunit/src/Framework/TestResult.php:698
/vagrant/www/timber/vendor/phpunit/phpunit/src/TextUI/TestRunner.php:545

3) TestTimberPost::testPostWithVideo
Failed asserting that two arrays are equal.
--- Expected
+++ Actual
@@ @@
 Array (
-    0 => '<iframe width="500" height="281" src="https://www.youtube.com/embed/Jf37RalsnEs?feature=oembed" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>'
+    0 => '<iframe title="Building sane, reusable WordPress templates with Twig and Timber - WPCampus 2017" width="500" height="281" src="https://www.youtube.com/embed/Jf37RalsnEs?feature=oembed" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>'

/vagrant/www/timber/vendor/phpunit/phpunit/src/Framework/Constraint/IsEqual.php:136
/vagrant/www/timber/tests/test-timber-post.php:816
/vagrant/www/timber/vendor/phpunit/phpunit/src/Framework/TestResult.php:698
/vagrant/www/timber/vendor/phpunit/phpunit/src/TextUI/TestRunner.php:545

4) TestTimberRouter::testRouterClass
Failed asserting that false is true.

/vagrant/www/timber/vendor/phpunit/phpunit/src/Framework/Constraint/Constraint.php:117
/vagrant/www/timber/vendor/phpunit/phpunit/src/Framework/Constraint/Constraint.php:62
/vagrant/www/timber/tests/test-timber-router.php:33
/vagrant/www/timber/vendor/phpunit/phpunit/src/Framework/TestResult.php:698
/vagrant/www/timber/vendor/phpunit/phpunit/src/TextUI/TestRunner.php:545

5) TestTimberTerm::testTermWithNativeMetaNotExisting
Failed asserting that null is false.

/vagrant/www/timber/vendor/phpunit/phpunit/src/Framework/Constraint/Constraint.php:117
/vagrant/www/timber/vendor/phpunit/phpunit/src/Framework/Constraint/Constraint.php:62
/vagrant/www/timber/tests/test-timber-term.php:232
/vagrant/www/timber/vendor/phpunit/phpunit/src/Framework/TestResult.php:698
/vagrant/www/timber/vendor/phpunit/phpunit/src/TextUI/TestRunner.php:545

--

There were 11 risky tests:

1) TestTimberAdmin::testUpgradeMessage
This test did not perform any assertions

/vagrant/www/timber/vendor/phpunit/phpunit/src/Framework/TestResult.php:865
/vagrant/www/timber/vendor/phpunit/phpunit/src/TextUI/TestRunner.php:545

2) TestTimberClass::testConstantsDefining
This test did not perform any assertions

/vagrant/www/timber/vendor/phpunit/phpunit/src/Framework/TestResult.php:865
/vagrant/www/timber/vendor/phpunit/phpunit/src/TextUI/TestRunner.php:545

3) TestTimberPagination::testPaginationInCategory
This test did not perform any assertions

/vagrant/www/timber/vendor/phpunit/phpunit/src/Framework/TestResult.php:865
/vagrant/www/timber/vendor/phpunit/phpunit/src/TextUI/TestRunner.php:545

4) TestTimberPostQuery::testBackwards
This test did not perform any assertions

/vagrant/www/timber/vendor/phpunit/phpunit/src/Framework/TestResult.php:865
/vagrant/www/timber/vendor/phpunit/phpunit/src/TextUI/TestRunner.php:545

5) TestTimberPostComments::testThreadedCommentsWithTemplate
This test did not perform any assertions

/vagrant/www/timber/vendor/phpunit/phpunit/src/Framework/TestResult.php:865
/vagrant/www/timber/vendor/phpunit/phpunit/src/TextUI/TestRunner.php:545

6) TestTimberPostGetter::test587
This test did not perform any assertions

/vagrant/www/timber/vendor/phpunit/phpunit/src/Framework/TestResult.php:865
/vagrant/www/timber/vendor/phpunit/phpunit/src/TextUI/TestRunner.php:545

7) TestTimberPost::testNextWithDraft
This test did not perform any assertions

/vagrant/www/timber/vendor/phpunit/phpunit/src/Framework/TestResult.php:865
/vagrant/www/timber/vendor/phpunit/phpunit/src/TextUI/TestRunner.php:545

8) TestTimberTermTwigFilters::testTwigFilterDateI18n
This test did not perform any assertions

/vagrant/www/timber/vendor/phpunit/phpunit/src/Framework/TestResult.php:865
/vagrant/www/timber/vendor/phpunit/phpunit/src/TextUI/TestRunner.php:545

9) TestTimberTermTwigFilters::testTwigFilterDateI18nWordPressOption
This test did not perform any assertions

/vagrant/www/timber/vendor/phpunit/phpunit/src/Framework/TestResult.php:865
/vagrant/www/timber/vendor/phpunit/phpunit/src/TextUI/TestRunner.php:545

10) TestTimberWPFunctions::testInTwig
This test did not perform any assertions

/vagrant/www/timber/vendor/phpunit/phpunit/src/Framework/TestResult.php:865
/vagrant/www/timber/vendor/phpunit/phpunit/src/TextUI/TestRunner.php:545

11) TestTimberWPFunctions::testInTwigString
This test did not perform any assertions

/vagrant/www/timber/vendor/phpunit/phpunit/src/Framework/TestResult.php:865
/vagrant/www/timber/vendor/phpunit/phpunit/src/TextUI/TestRunner.php:545

ERRORS!
Tests: 706, Assertions: 1142, Errors: 20, Failures: 5, Skipped: 8, Risky: 11.
```

**Comment by gchtr** [comment]
Why is this pull request against the `master` branch? Shouldn’t it be against the `2.x` branch?

**Comment by gchtr** [comment]
I found the error for the `Cannot redeclare Timber\Timber::$version` error: https://github.com/timber/timber/pull/1617/commits/8d0263dd7f815aeb8818b7821035409af961f481#diff-29bdb2cadf10c2dd9113be31487d6e67L44.

Probably introduced when merging the master branch into 2.x.

Btw, PhpStorm has the best tool for resolving merge conflicts I’ve found so far. You don’t even have to use the rest of PhpStorm’s version control system for this. It’s fine to just use it for merge conflicts.

**Comment by acobster** [comment]
Thanks @jarednova !

Yes, it should be against `2.x`. Not sure why it was `master`. I will definitely look into PHPStorm for resolving conflicts.

**Comment by acobster** [comment]
@pascalknecht what should we do about querying multiple posts? I noticed this in `PostGetter`:

```php
	// TODO is this right?
	public static function get_posts( $query = false, $PostClass = '', $return_collection = false ) {
		add_filter('pre_get_posts', array('Timber\PostGetter', 'set_query_defaults'));
		$posts = self::query_posts($query, $PostClass);

		/**
		 * Filters the posts returned by `Timber::get_posts()`.
		 *
		 * There’s no replacement for this filter, because it’s called in a function that will be
		 * removed in the future. If you’re using `Timber::get_posts()`, you should replace it with
		 * `new Timber\PostQuery()`.
		 *
		 * @deprecated 2.0.0
		 */
		$posts = apply_filters_deprecated(
			'timber_post_getter_get_posts',
			array( $posts->get_posts( $return_collection ) ),
			'2.0.0',
			false,
			'There’s no replacement for this filter, because it’s called in a function that will be removed. If you’re using Timber::get_posts(), you should replace it with new Timber\PostQuery().'
		);

		return $posts;
	}
```

Is the plan to make `PostQuery` the go-to solution for this use-case, and making it use `PostFactory` under the hood? If so, should we do that as part of this PR, or just shim it for now to get the tests passing?

**Comment by pascalknecht** [comment]
@acobster Yeah I think everything should use the Post Factory under the hood. Would be probably best to continue here so that we have all discussion here in this thread.

**Comment by pascalknecht** [comment]
> I guess __construct doesn't need to take any arguments now, and if people really want to bootstrap some internal state they still can. So, I don't really see any reason to keep the default constructor around...is that your thinking?

Yeah we can remove the default contructor and just do everything in the factory. That would be the best I think.

**Comment by acobster** [comment]
@gchtr great questions. I definitely don't know the answer to all of them. :)

> * Is the logic from #1793 (comment) already included in this pull request?

Not all of it. I think there are still a few instances where the new API is still broken. (I want to try to get all the tests passing again, or at least the right ones failing, before I try to hack at the factory code any more. I haven't tried this since Jared's most recent 2.x merge.)

> We also agreed that the get() method always needs a post ID or an object. If a post can’t be found, it will return null.
> 
>     Should the get() method have a default of null for the $post_identifier or would that fall away?
> 
> Currently, the get() method lies in the Timber\Factory\PostFactory class.
> 
>     Would we move that over to Timber\Post or do we keep it in the factory and add Timber\Post::get() as a shorthand for the factory?

Not sure about these ones. @pascalknecht ? Having two seems like it would be confusing and unnecessarily complicated. I don't really see a compelling argument _not_ have a `Post::get()` ...but if we did, what would be the point of exposing `PostFactory::get()`? Perhaps the Factory one should remain hidden? We could still allow people to swap out Factory implementations if they really needed to through filters, but maybe Factories don't need to be part of the public API after all.

> Because get_object() is public, I assume there’s a case where we call get_object() directly? When is that?

I'm not convinced that `get_object()` should be public. I'm looking into making this protected or private. (I'm also not totally convinced that we need an `ObjectClassFactory`; seems like the kind of thing that could be refactored away to a private instance methods, a sensible array of default mappings, and a well-placed filter.)

I will try to circle back to the other questions about PostQuery, Users, and Comments, but in short, I think the 1.x APIs for all of those things suffer from the same problems that Posts do, and should all be driven by Factories under the hood.

**Comment by pascalknecht** [comment]
@acobster makes sense. We should probably just have Post::get() and all related functions (Comment::get, etc.). We should then be careful to just let the users use these API's and hide the rest of the implementation such that they cannot be accessed.

**Comment by acobster** [comment]
Closing this, but work on Factories will continue in #2093. Thanks so much for your contributions to this effort, @joshlevinson !

**Comment by joshlevinson** [comment]
Thanks for taking the charge and pushing the idea forward to reality!

**Pull request closed without merging**
