### PR TITLE
allow overriding default lifetime of {% cache %}-created transients i…

### PR DESCRIPTION
**Pull request by salaros**
**Ticket**: #1609 

#### Issue
{% cache %}-generated transient items never expire and are auto-loaded by WordPress by default. So both performance and database size are affected.

#### Solution
The small change I made allow theme designers to override the behavior above and make GCS-<hash>-suffixed transient items expirable and not auto-loaded.

#### Impact
If one won't implement add_filter('timber/cache/extension/lifetime', ....); WordPress filter, nothing in default Timber behavior changes, so IMO there is no serious impact to the code base.

#### Usage Changes
Now theme developers can make {% cache %}-generated transient items expirable by implementing `timber/cache/extension/lifetime` filter:
```php
add_filter('timber/cache/extension/lifetime', function() {
        return HOUR_IN_SECONDS * 24;
});
```

#### Considerations
Frankly I don't know if all Timber users use [WP Cron](https://developer.wordpress.org/plugins/cron/scheduling-wp-cron-events/) in order to solve the issue described in #1609 and clear all previously-created and potentially unused transient items. If they don't even know about this problem, we'd consider the possibility to set the default cache strategy lifetime to something other than 0.

#### Testing
Nope. Unfortunately I have a lot of time now. The last time [I contributed to Timber](https://github.com/timber/timber/pull/861) I created tests, but this time I don't think I can do it. However if nobody can help us out with it I will create a unit test.

### CODE REVIEW

**Comment by salaros** [comment]
As you might have noticed the build failed because of some complely unrelated functionality

**Comment by jarednova** [comment]
Thanks @salaros — re-ran those tests against the new `master` (looks like something changed in WP with how those un-related media tags were built). Merged!

**Comment by salaros** [comment]
Wow, thanks @jarednova I will send a PR with unit tests shortly

**Comment by jarednova** [comment]
Thanks @salaros. Does this close #1609?

**Comment by salaros** [comment]
Yeap

**Pull request merged**
