### PR TITLE
Fix: LocationManager returns wrong locations in child themes

### PR DESCRIPTION
**Pull request by pratik-londhe4**
Related:

- #2843

## Issue

- Child theme not able to override templates of the parent theme due to wrong locations array.
## Solution

- This solution was proposed in #2843 by @palttamas but I could not find PR related to it so creating this

## Usage Changes

- None

### CODE REVIEW

**Comment by Levdbas** [comment]
Hi @pratik-londhe4 , thank you for taking a shot at this. Though your fix seems different from what @palttamas suggested in  https://github.com/timber/timber/issues/2843#issuecomment-1846757344 ?

```php
--$locs = \array_merge_recursive($locs, self::get_locations_theme());
--$locs = \array_merge_recursive($locs, self::get_locations_caller($caller));
++$locs = array_diff($locs, self::get_locations_theme());
++$locs = array_merge_recursive($locs, self::get_locations_theme());
```

**Comment by pratik-londhe4** [comment]
hi, @levdbas. 
This `$locs = array_merge_recursive($locs, self::get_locations_theme());` is already present in the get_locations, so adding it again is unnecessary.

I have tested these changes in a child theme setup.

**Comment by Levdbas** [comment]
Hi @pratik-londhe4 , unfortunately the tests fail. Are you willing to take another look at this?

**Comment by palttamas** [comment]
> Hi @pratik-londhe4 , unfortunately the tests fail. Are you willing to take another look at this?

Hey, just chipping in. I did try to fix the issue, tried couple of variations but as @Levdbas is saying, the tests fail, at which point I quickly lost interest, since we resolved this thing internally with a filter anyway.

**Comment by pratik-londhe4** [comment]
@Levdbas , sure I will take look at failing tests and find solution for it.

**Comment by okadots** [comment]
I was having this same issue and adding `$locs = array_diff($locs, self::get_locations_theme());` as described above fixed the problem, but we are also seeing the `Array to string conversion` error noted [here](https://github.com/timber/timber/issues/2843#issuecomment-1844948922)

We are upgrading from the old Timber WP plugin, where we were not having this issue. I went back and looked at the old plugin code and that `array_diff` line is present.

UPDATE:
In our case, the parent theme is never used on it's own - it is used as a framework that can be customized in the child theme. I simply changed the order of the arrays in the array merge so that the current theme (child) locations come first. _This has not been thoroughly tested on a site that only uses the parent theme and this may not be the final fix_

`$locs = \array_merge_recursive($locs, self::get_locations_theme());`  becomes => 
`$locs = \array_merge_recursive(self::get_locations_theme(), $locs);`

**Comment by Levdbas** [comment]
Hi @pratik-londhe4 , I fixed this up in  #2925. Everyone, thank you for your input on this.

**Pull request closed without merging**
