### PR TITLE
1227 image test fix

### PR DESCRIPTION
**Pull request by jarednova**
**Ticket**: #1227 

We might have gotten a little ambitions with replacing `site_url` with `get_home_url()`. I found some errors in tests relating to WPML and external images. This splits the tests to better measure and resolves errors

### CODE REVIEW

**Comment by jarednova** [comment]
@jnweaver — I was seeing URLs like this coming back from remotely downloaded images with WPML:

http://example.org/en/wp-content/uploads/2016/11/fc990091d1d3ef80591db58450e4dc09.jpg

by restoring [Timber\ImageHelper:370](https://github.com/timber/timber/blob/9d3ada98c56fec3755902e42bd0c627918d89d0a/lib/ImageHelper.php#L370) back to `site_url` (instead of `get_home_url`) fixed this. Does this undo your work in #1227 ? Your other changes of `site_url` => `get_home_url` still remain

**Comment by jnweaver** [comment]
Hi @jarednova -- I think you meant to tag @njbarrett on this.

**Comment by jarednova** [comment]
@jnweaver whoops!!! my bad! @njbarrett: I was seeing URLs like this coming back from remotely downloaded images with WPML:

`http://example.org/en/wp-content/uploads/2016/11/fc990091d1d3ef80591db58450e4dc09.jpg`

by restoring [Timber\ImageHelper:370](https://github.com/timber/timber/blob/9d3ada98c56fec3755902e42bd0c627918d89d0a/lib/ImageHelper.php#L370) back to `site_url` (instead of `get_home_url`) fixed this. Does this undo your work in #1227 ? Your other changes of `site_url` => `get_home_url` still remain

**Comment by njbarrett** [comment]
Hey @jarednova , confirming that these changes still work for me.

Before my changes I was seeing URLs like:
`/http://example.org/en/wp-content/uploads/2016/11/fc990091d1d3ef80591db58450e4dc09.jpg`

(note the extra slash at the front)

But this seems fixed even with reverting one of the get_home_url() calls. So I'm happy for this.

**Comment by jarednova** [comment]
awesome! lets merge!

**Pull request merged**
