### PR TITLE
2.x Remove action context

### PR DESCRIPTION
**Pull request by gchtr**
**Ticket**: #1528

## Issue

Timber adds an `action` function for Twig like this:

```php
$twig->addFunction( new Twig_Function( 'action', function( $context ) {
    $args = func_get_args();
    array_shift( $args );
    $args[] = $context;
    call_user_func_array( 'do_action', $args) ;
}, array( 'needs_context' => true ) ) );
```

This function will always add the context as the last parameter in the hook, so that it can be used like this:

```php
<?php
add_action( 'my_action_with_args', 'my_function_with_args', 10, 3 );

function my_function_with_args( $foo, $bar, $context ){
    echo 'I say ' . $foo . ' and ' . $bar;
    echo 'For the post with title ' . $context['post']->post_title;
}
```

As I see it, this was added so that developers can add their own actions and receive the context, should they need it in the hook.

Like mentioned in the ticket, there can be problems: When you don’t pass in any parameters, Timber will automatically add the context as the first parameter. This can lead to unexpected behavior, because the action function receives a parameter although you might not have passed one when you used `{% do action() %}`.

Consider this example, where a plugin might add an action that receives a string:

```php
<?php
add_action( 'aye_aye', function( $string ) {
    echo 'I say ' . $string;
}, 10, 1 );
```

You could call the action like this, without an argument:

```twig
{% do action('aye_aye') %}
```

Timber would now pass a `$context` array to the action, which would lead to an array-to-string conversion error, because the action echoes out the string, which is an array in this case.

When calling `do_action`, Timber doesn’t know which functions will be called and how many arguments they will receive. Maybe we could read this out, but should we? And do we have to?

In my opinion, we should simply make it possible to call `do_action` and not try to do some magic here. The required arguments for `do_action` should just be passed in manually.

## Solution

- Delete functionality that adds the context automatically.
- Delete tests.
- Update documentation.

## Impact

This will break calls with `{% do action() %}` that relied on the context in an argument. That’s why it’s a good place to add it to version 2.0.

## Usage Changes

Hooks that expect the context to be passed as the last argument will have to be adapted so that the required arguments can be passed manually. So the example mentioned earlier would have to be rewritten like this:

```php
<?php
add_action( 'my_action_with_args', 'my_function_with_args', 10, 3 );

function my_function_with_args( $foo, $bar, $post ){
    echo 'I say ' . $foo . ' and ' . $bar;
    echo 'For the post with title ' . $post->post_title;
}
```

The post will be passed manually as a third argument.

```twig
{% do action( 'my_action_with_args', 'Yippie', 'Yeah', post ) %}
```

## Considerations

Did I forget to consider something?

## Testing

I removed the relevant tests.

### CODE REVIEW

**Comment by jarednova** [comment]
Thanks @gchtr, reviewing now!

**Comment by jarednova** [comment]
Looks good! I made two small changes...

- Updated the docs to show an example of using a "template" variable in an action
- Used this as an opportunity to run coverage tests on things merging into 2.x (I was curious to see if we lost test coverage %%, we didn't)

**Comment by gchtr** [comment]
Cool thing about the example in the documentation!

**Comment by jarednova** [comment]
📜📜📜📜📜

**Pull request merged**
