### PR TITLE
Set user password to be hidden by default

### PR DESCRIPTION
**Pull request by lggorman**
**Ticket**: #1073 
**Reviewer**: @jarednova 

#### Issue
As described in #1073, the user's hashed password exposed is in the TimberUser object.

#### Solution
Added an `include_pass` flag to the constructor and init functions, which is set to false by default.  Unless the flag is set to true, the user password will not be exposed in the user object.   

#### Impact
Would only affect users that are using that hashed password somewhere, which seems like an edge case.

#### Usage
The TimberUser constructor now accepts an optional second param, the `include_pass` flag.  

#### Considerations
-

#### Testing
Tests are included!

### CODE REVIEW

**Comment by lggorman** [comment]
@jarednova Should I revise this? Maybe it would be better to just make it protected instead of unsetting it entirely.

**Comment by jarednova** [comment]
@lggorman — can you look at some of the comments in #1073? My inclination is to unset with no ability to access the user's PW. The two biggest potential vulnerabilities I see are...

1) A `print_r` either in a template or using the Timber Debug Bar
2) A user having access to a template editor which would allow them to do something like `{{ TimberUser(4).user_pass }}` and have access to any user's (hashed) PW

I can't think of a use case where you'd ever want to display or access this data. I see a far greater risk in both exposing this and giving the appearance that Timber is less than secure. 

Your revision could be as simple as removing the `$include_pass` flag functionality

**Comment by lggorman** [comment]
@jarednova Makes sense to me, got rid of the password flag

**Comment by jarednova** [comment]
Awesome, thanks @lggorman !

**Pull request merged**
