### PR TITLE
Fix TimberImage\init_with_url() not working in bedrock environment

### PR DESCRIPTION
**Pull request by oxyc**
**Ticket**: #1458
#### Issue

If you init a TimberImage by url it sets the incorrect `file_loc` property using `ABSPATH` which points to the wp core directory.

#### Solution

Analyze `content_url()` and `site_url()`, if different find where their path differs and remove that part from `ABSPATH`.

```
# Bedrock
ABSPATH: /var/www/wordpress/wp
WP_CONTENT_DIR: /var/www/wordpress/app
-> /var/www/wordpress
-> /var/www/wordpress/app/uploads/

# Regular
ABSPATH: /var/www/wordpress
WP_CONTENT_DIR: /var/www/wordpress
-> /var/www/wordpress
-> /var/www/wordpress/app/uploads/

# Subdir
ABSPATH: /var/www/wordpress/subdir/wp
WP_CONTENT_DIR: /var/www/wordpress/subdir/app
-> /var/www/wordpress/subdir
-> /var/www/wordpress/subdir/app/uploads/
```

Some notes:
- Can't use `dirname($_DOCUMENT['SCRIPT_NAME'])` as this needs to work with phpunit as well. Possibly with WP-CLI at some point.
- Need to use the URL functions rather than `ABSPATH` and `WP_CONTENT_DIR` as there's otherwise no way to test it. Unless we somehow could modify `ABSPATH` in these particular tests.

#### Impact

This might cause a performance hit because of `get_root_dir()` being called multiple times.

#### Usage

None.

#### Documentation Requirements:
Check one:
- [x] No usage changes. I've updated the `readme.txt` with a quick summary of the change and my GitHub handle
- [ ] Yes, there's a usage change. I've updated the `readme.txt` with ...
  - [ ] **Change for Theme Developers:** label
  - [ ] A quick summary of the change
  - [ ] New usage instructions

#### Considerations

Might consider caching the result of `get_root_dir()` so improve performance. Also, if this feels too complex maybe just default to `ABSPATH` but add a filter to `get_root_dir()` that allows users to manually specifiy the webroot.

#### Testing

I added tests for the `file_loc` property and normalized the WPML prefix tests so that `ICL_LANGUAGE_CODE` is set and the new WPML integration fixes the URLs.

I'm still not 100% confident in this solution but thought I'd share it at least. If nothing else you can use 75dce024e93674620b82a43c994a8480f5f16aea as a way to test that a solution fixes the issue.

### CODE REVIEW

**Comment by oxyc** [comment]
As tests pass locally I assume in Travis `get_root_dir()` for some reason resolves to `/` consequently removing all slashes. I'll look into it again when I have time.

**Comment by jarednova** [comment]
Thanks @oxyc — this is the next one up in my list!

**Comment by oxyc** [comment]
@jarednova not sure how to fix this to be honest :) Maybe you can figure something out. Currently I'm just using a custom Timber\Image subclass and fix `file_loc` on init

**Comment by jarednova** [comment]
Closing as stale!

**Pull request closed without merging**
