### PR TITLE
Enforce Line Length Rule

### PR DESCRIPTION
**Pull request by jarednova**
#### Issue
Line lengths are inconsistent

#### Solution
Per @gchtr's suggestion, introduce a line length rule into the `phpcs.xml` file to help standardize line lengths

#### Impact
Might introduce some additional warnings in Scrutinizer

### CODE REVIEW

**Comment by jarednova** [comment]
@gchtr Since this is a docs/style thing, can you give this a glance? As expected, it triggers a bunch of new Scrutinizer warnings:

https://scrutinizer-ci.com/g/timber/timber/inspections/923f6a25-88f8-4f55-8abf-e327cc2854b9/issues/files/lib/Admin.php?status=new&orderField=path&order=asc&honorSelectedPaths=0

**Comment by gchtr** [comment]
@jarednova So do you want me to fix these issues now or wait until we dig through the whole codebase to apply the new coding standards?

**Comment by jarednova** [comment]
I was going to file those under "wait." Similar how we're doing other stuff: correct docs style +line_length issues are we get to certain sections of code. For now, just ensure that the rule matches your expectations/approval

**Comment by gchtr** [comment]
For me, this looks good! When we’d really need more control in code, we could [ignore certain lines](https://github.com/squizlabs/PHP_CodeSniffer/wiki/Advanced-Usage#ignoring-parts-of-a-file). For comments, long links shouldn’t trigger a warning, and as it seems, they don’t:

phpcs-warnings

So in my humble opinion: Looks good! 👍

**Comment by jarednova** [comment]
cool, let's do it then!

**Pull request merged**
