### PR TITLE
Static analysis fixes

### PR DESCRIPTION
**Pull request by szepeviktor**
Was #1986

### CODE REVIEW

**Comment by szepeviktor** [comment]
Remaining ones:

```
 ------ -------------------------------------------------------------------------------------
  Line   Attachment.php
 ------ -------------------------------------------------------------------------------------
  136    Timber\Attachment::__construct() does not call parent constructor from Timber\Post.
 ------ -------------------------------------------------------------------------------------

 ------ --------------------------------------------------------------------
  Line   Comment.php
 ------ --------------------------------------------------------------------
  288    Access to an undefined property Timber\Comment::$comment_approved.
  373    Access to an undefined property Timber\Comment::$comment_parent.
 ------ --------------------------------------------------------------------

 ------ --------------------------------------------------------------------------------------
  Line   Image.php
 ------ --------------------------------------------------------------------------------------
  95     Timber\Image::__construct() does not call parent constructor from Timber\Attachment.
  129    Access to an undefined property Timber\Image::$_dimensions.
  144    Access to an undefined property Timber\Image::$_dimensions.
  146    Access to an undefined property Timber\Image::$_dimensions.
 ------ --------------------------------------------------------------------------------------

 ------ -------------------------------------------------------------------
  Line   ImageHelper.php
 ------ -------------------------------------------------------------------
  169    Variable $file_path in isset() always exists and is not nullable.
 ------ -------------------------------------------------------------------

 ------ ---------------------------------------------------------------------------------
  Line   Integrations/CoAuthorsPlusUser.php
 ------ ---------------------------------------------------------------------------------
  40     Access to an undefined property Timber\Integrations\CoAuthorsPlusUser::$avatar.
 ------ ---------------------------------------------------------------------------------

 ------ -----------------------------------------------------------
  Line   MenuItem.php
 ------ -----------------------------------------------------------
  82     Access to an undefined property Timber\MenuItem::$name.
  83     Access to an undefined property Timber\MenuItem::$name.
  161    Access to an undefined property Timber\MenuItem::$custom.
 ------ -----------------------------------------------------------

 ------ ---------------------------------------------------------
  Line   Site.php
 ------ ---------------------------------------------------------
  219    Access to an undefined property Timber\Site::$pingback.
 ------ ---------------------------------------------------------

 ------ -------------------------------------------------------
  Line   Term.php
 ------ -------------------------------------------------------
  142    Access to an undefined property Timber\Term::$custom.
 ------ -------------------------------------------------------

 ------ -------------------------------------------------------
  Line   User.php
 ------ -------------------------------------------------------
  164    Access to an undefined property Timber\User::$custom.
 ------ -------------------------------------------------------
```

**Comment by szepeviktor** [comment]
On Level 2 and higher numerous errors are revealed.

**Comment by jarednova** [comment]
For now, this is just some small fixes in docblocks. Can one of the 2.x committers give this a quick look? Fine to keep this PR small, easier to deal with small changes than big changes

**Comment by szepeviktor** [comment]
I am encouraging you to fix all Level 2 errors as the first step, see #1986

**Comment by szepeviktor** [comment]
@acobster FYI PHPStan is not (_yet_) integrated in CI.

**Comment by jarednova** [comment]
@acobster that's my error: accidentally had it testing against WP 5.9.2 (instead of 5.3.2) — fixed!

**Comment by jarednova** [comment]
@gchtr can you take final review + merge on this one?

**Comment by gchtr** [comment]
Thanks @szepeviktor for taking the time to create a pull request with these fixes 👍

**Comment by szepeviktor** [comment]
You're welcome.

**Pull request merged**
