### PR TITLE
1974 wpml menu fix

### LINKED ISSUE #1974: Issue with Menu in WPML
Recently we had issue in our support forum related to your plugin and WPML compatibility, here: https://wpml.org/forums/topic/language-switch-as-last-item-in-menu-inherits-custom-class-names/

Can you please check it out, I am providing fix as well.:

In this file /wp-content/plugins/timber-library/lib/Menu.php
After line 253 change this:

```php
if ( isset($item->ID) ) {
                if ( is_object($item) && get_class($item) == 'WP_Post' ) {
                    $old_menu_item = $item;
                    $item = new $this->PostClass($item);
                }
                $menu_item = $this->create_menu_item($item);
                if ( isset($old_menu_item) ) {
                    $menu_item->import_classes($old_menu_item);
                }
                $index[$item->ID] = $menu_item;
            }

```
Into this:

 ```php
      if ( isset($item->ID) ) {
                if ( is_object($item) && get_class($item) == 'WP_Post' ) {
                    $old_menu_item = $item;
                    $item = new $this->PostClass($item);
                }
                if ( get_class($item) == 'WPML_LS_Menu_Item' ) {
                    $old_menu_item = $item;
                }
                $menu_item = $this->create_menu_item($item);
                if ( isset($old_menu_item) ) {
                    $menu_item->import_classes($old_menu_item);
                }
                $index[$item->ID] = $menu_item;
            }
   
```

### PR DESCRIPTION
**Pull request by jarednova**
**Ticket**: #1974 

## Issue
The last WPML language switcher menu item was picking up the prior item's classes

## Solution
While we want to use the `WP_Post` object (as opposed to the Timber-based object) to pull classes from, we need to clear its value to prevent the issue from occurring

## Impact
This fixes #1974 (including @mgarabedian related issue). Unlike #2009, this isn't WPML-specific

## Usage Changes
None

## Testing
I tested locally against a real WPML instance and verified the fix. I don't think new tests are necessary since this removes a bug vs. creating a feature

### CODE REVIEW

**Comment by jarednova** [comment]
This is ready for your review @palmiak !

**Comment by palmiak** [comment]
@jarednova do we have some access to latest WPML? I only have some older version from some project.

**Comment by jarednova** [comment]
@palmiak yeah, they gave me a dev copy to test against. I'll email you what I've got

**Comment by roberrrt-s** [comment]
Hi @jarednova does this commit fix issue #2020 ?

**Comment by jarednova** [comment]
@roberrrt-s #2020 is resolved by a (pending) upgrade to WPML that will synchronize versions of Twig. Once it's released I'll test to verify and then (very loudly) annouce

**Pull request merged**
