### PR TITLE
Changing static call to regular call

### PR DESCRIPTION
**Pull request by connorjburton**
Can you please merge and release @jarednova - just a small bug with `1.0.4`

Merci!

### CODE REVIEW

**Comment by jarednova** [comment]
@connorjburton thanks for the fix! The failing tests are just for a problem with the gravatar server, we can ignore those. However, since `Timber::compile` is a static function, wouldn't the call to `init` also need to be static — `$this` wouldn't be available, right? Or am I missing something here?

**Comment by connorjburton** [comment]
Oh yeah gotcha, will change that now

**Comment by connorjburton** [comment]
How's that?

**Comment by jarednova** [comment]
That'll do it! I'm just re-running the tests with the latest master and will merge!

**Pull request merged**
