### PR TITLE
Run WebP related tests also

### PR DESCRIPTION
**Pull request by szepeviktor**
From https://github.com/timber/timber/pull/2319#issuecomment-683980238

@jarednova Here we(bp) go!

### CODE REVIEW

**Comment by szepeviktor** [comment]
> OK (6 tests, 18 assertions)

🍏

**Comment by szepeviktor** [comment]
Will adding `--stop-on-skipped` make skipped tests error out??

**Comment by jarednova** [comment]
WOW, that was quick!

> Will adding --stop-on-skipped make skipped tests error out??

It stops the tests, however the result isn't an error ...
Screen Shot 2020-08-31 at 10 04 18 PM

**Comment by szepeviktor** [comment]
Sad!

Please merge.

**Comment by jarednova** [comment]
Excellent! I like how this keeps the webp tests separate (and a breezy 2:29 to run). Even if a small amount of time could be saved by merging it with one of the other 7.2 tests; I think it's easier to manage as its own element to enable/disable/update as we need

**Pull request merged**
