### PR TITLE
Update compatibility checks

### PR DESCRIPTION
**Pull request by nlemoine**
- Remove the Twig check, 2.x is now a pure PHP package
- Update PHP check

### CODE REVIEW

**Comment by nlemoine** [comment]
I event think PHP check should be skipped. Since you're supposed to install with composer, it will warn you if the package isn't compatible with your PHP version. No composer package does that check.

**Comment by gchtr** [comment]
> I event think PHP check should be removed. Since you're supposed to install Timber with composer, it will warn you if the package isn't compatible with your PHP version. No composer package does that check.

Yes, that’s what I thought, too, when I checked your changes in this pull request 👍. I think the check can go.

**Review by jarednova — DISMISSED** [review]
Agreed! This is a remnant of the WP install method

**Comment by jarednova** [comment]
@nlemoine this is ✅ ! With your new powers/permissions can you hit the green button?

**Comment by nlemoine** [comment]
Sorry @jarednova, the PHP check removal was missing, can you approve this again? 😅

**Review by jarednova — APPROVED** [review]

**Pull request merged**
