### PR TITLE
Add image convert to webp

### PR DESCRIPTION
**Pull request by mhz-tamb**
**Ticket**: # 

#### Issue

Using images lighter than jpg

#### Solution

Allows to convert images to webp like tojpg

#### Impact

None

#### Usage Changes

Added a simple example in the documentation

#### Testing

Tests are included, and run without problems

### CODE REVIEW

**Comment by mhz-tamb** [comment]
Hello! Do I need any changes?
In travis my tests break down. I think this is related to this issue https://github.com/travis-ci/travis-ci/issues/8435
Will this be ok if I check the existence of the imagewebp function in the tests for skip it?

**Comment by pascalknecht** [comment]
Any updates on this PR?

**Comment by jarednova** [comment]
@mhz-tamb @pascalknecht — thanks for your patience! I just got back last week from a paternity leave and this PR is next on my plate

**Comment by jarednova** [comment]
@mhz-tamb @pascalknecht thanks again for the PR and your patience. As @mhz-tamb points out there is a Travis limitation on testing for webp — that said, things pass for me locally. I want to make sure we account for webp in the future, so here are two possible mitigations:

1) Using the guidance of [#8435](https://github.com/travis-ci/travis-ci/issues/8435) figure out how to enable `imagewebp` in the PHP Travis build we're using
2) Skip the tests if `imagewebp` is not available.

@mhz-tamb — can you pick things back up from here?

**Pull request merged**
