### PR TITLE
Alias Twig_Function from Twig 2.4.0

### PR DESCRIPTION
**Pull request by nlemoine**
**Ticket**: #1632

#### Issue
From 2.4.0, Twig does not allow `Twig_Function` class to be extended. Triggers PHP notices if using Twig ^2.4.0

#### Solution
Alias class and map it to new Twig class `\Twig\TwigFunction`.

#### Impact

Locally tested with Twig ^1.0|2.3.0|^2.4.0, looks fine.

#### Usage Changes

None.

#### Considerations

Require Twig ^2.4.0. PHP 7+ is now available on any decent hosting provider.

#### Testing

Sorry, no. I don't know how to deal with multiple versions of a package with `phpunit`.

### CODE REVIEW

**Comment by jarednova** [comment]
Thank you @nlemoine — looking into how (if) we can test against diff't versions of dependencies.

**Comment by jarednova** [comment]
@nlemoine I tested and was not able to get any errors/warnings pre-patch. What log or location are you seeing these? It looks like in the code there's a `@final` designation on the class but not in the class declaration itself:

https://github.com/twigphp/Twig/blob/2.x/lib/Twig/Function.php#L15

... can you confirm this? If this is a future-proof sort of thing, I'm still in total support. I just want to make sure I'm evaluating against the correct thing

**Comment by nlemoine** [comment]
@jarednova Error doesn't show up because there's an error control operator `@` before `trigger_error`. 

You can see it when using a custom error handler such as [Query Monitor](https://github.com/johnbillion/query-monitor/blob/master/collectors/php_errors.php#L92-L95) or [Wonolog](https://github.com/inpsyde/Wonolog).

However, Twig will soon forbid the current behavior. The patch will make Timber Twig 3.0 ready.

**Comment by jarednova** [comment]
Perfect, now I see it!

**Comment by nlemoine** [comment]
> looking into how (if) we can test against diff't versions of dependencies.

@jarednova Just stumbled upon this post: https://blog.martinhujer.cz/17-tips-for-using-composer-efficiently/
Look at tip #7, it might be a good way to test Timber against different versions of Twig.
I gave it a try here: https://travis-ci.org/nlemoine/timber/builds/337731007

**Pull request merged**
