### PR TITLE
ref #429 -- fixed server location to build-in filter fix

### PR DESCRIPTION
**Pull request by jarednova**
**Ticket**: #429

#### Issue
#429 and #1131 describe issues where images stored on Amazon S3 do not load from S3 when Timber is activated

#### Solution
Apply a widely-used patch directly to `Timber\Image`: 

```php
// Add this to functions.php
function fix_timber_s3_src( $src, $ID ) {
    $size = '';
    $attachment_src = wp_get_attachment_image_src($ID, $size)[0];
    $fixed_src = $attachment_src ? $attachment_src : $src;
    return $fixed_src;
}
add_filter( 'timber_image_src', 'fix_timber_s3_src', 10, 2 );
```

#### Impact
Makes is cleaner! But also could have fallout based on what's being over-written

#### Usage
None

#### Considerations
This does NOT solve the resizing issues described in #429 

#### Testing
Tests pass locally, no new tests though

### CODE REVIEW

**Comment by jarednova** [comment]
@tvanantwerp can you review and see if this solves the issues for you in #429?

**Comment by tvanantwerp** [comment]
Output of `post.thumbnail.src` and sized variants exactly matches the expected S3 URLs with these changes.

I have no idea how the line deletions in the `src` function will affect any other Timber\Image or Timber\ImageHelper functions, if at all--but I pretty much only ever used `post.thumbnail.src` and wouldn't notice any potential side effects.

---

Not directly related to #429 but when I tested `post.thumbnail.width` or `post.thumbnail.height`, it returns `NULL`. Not something I really need or is within the scope of that issue and the bounty, but thought it worth mentioning. I've used `{{function('getimagesize', post.thumbnail.src)[0]}}` as a workaround in rare cases when I want that info. I know that `wp_get_attachment_image_src` also returns the image dimensions, so I imagine `width` and `height` could be fixed similarly if it's not just me experiencing the problem.

**Comment by jarednova** [comment]
Great, thanks @tvanantwerp! I figure while we're here I'd love to take care of the width/height stuff too, so I'll create a fresh issue + PR to work from on that front

**Comment by FlickerBean** [comment]
This merge results in a php >=5.4 requirement that did not previously exist in the codebase.

<php5.4 now throws

` PHP Parse error:  syntax error, unexpected '[' in /home/www.postalmuseum.org/the-postal-museum-2016/wordpress/wp-content/plugins/timber-library/lib/Image.php on line 444`

Due to 

`$src = wp_get_attachment_image_src($this->ID, $size)[0];`

**Comment by jarednova** [comment]
@davidmaneuver thanks for the heads-up on that; @gchtr submitted a fix in #1330 that I'll be releasing later today

**Pull request merged**
