### PR TITLE
Return correct menu_id when using WPML and 'theme_location' arg

### PR DESCRIPTION
**Pull request by mikeyb31**

### CODE REVIEW

**Comment by jarednova** [comment]
Excellent, thanks @mikeyb31! you're going to be a hero to a lot of users. Before I merge this in I wanted to see if you could look into writing a unit test. That way we can ensure that any future modifications to the code won't break what you've added. Rather than including all of the WPML plugin, we can potentially mock-in the response this function gives to test that functionality

**Comment by jarednova** [comment]
Thanks again @mikeyb31. I wrote a quick test and merged this in with #1437

**Comment by mikeyb31** [comment]
You're welcome @jarednova - apologies for not replying, I've been deep in other project work and wasn't too sure how you wanted me to approach the mock test.

**Comment by jarednova** [comment]
@mikeyb31 no prob!

**Pull request merged**
