### PR TITLE
1726/svg check

### PR DESCRIPTION
**Pull request by jarednova**
Tests and follow-up for #1726

### CODE REVIEW

**Comment by jarednova** [comment]
@palmiak thank you again for this contrib! Fixing some last style issues and will then merge. 

### Future possibilities:
- [ ] Allow SVGs to be converted to raster images (I attempted, but it seems to require additional libraries that we can't count on)
- [ ] Allow PDFs and other non-raster image media types to be handled with similar logic

**Comment by palmiak** [comment]
I saw that SVG could also be saved as plain text. I'll add this today.

pon., 9 lip 2018, 21:14 użytkownik Jared Novack <notifications@github.com>
napisał:

**Comment by jarednova** [comment]
@palmiak — yep, one step ahead of you on the `text/plain`. As far as PDFs, etc. I think that's a next step from here after merging. The methods you created were non-public so I'm comfortable refactoring in the future to account for those — are you interested in picking that up as yr next PR from here?

**Comment by palmiak** [comment]
Of course I am :)

**Pull request merged**
