### PR TITLE
The 2.x Purge!

### PR DESCRIPTION
**Pull request by jarednova**
**Ticket**: #2323 

## Issue
Remove the classes we identified in #2323 

- [x] `PostGetter`
- [x] ... and tests
- [x] `TermGetter` 
- [x] ... and tests
- [x] Any old `$CommentClass` props and the like
- [x] `QueryIterator` 
- [x] ... and tests
- [x] `Timber_WP_CLI_Command.php` (or move to its own repo)

- [x] `Post::determine_id()` and possibly other methods

## Solution
Delete the classes. Ensure that Factories and other 2.x mechanisms are fully functional without these.

## Usage Changes
Everything in 2.x

## Considerations
It's been well considered

## Testing
Interested to see how this affects coverage score. Looking to bring that back up to come close to current 1.x levels

### CODE REVIEW

**Comment by acobster** [comment]
> `QueryIterator` ... and tests

@jarednova @gchtr I think we're ready to delete these. Of the remaining two tests in `test-timber-query-iterator.php`, one is already ported over into `test-timber-post-collection.php`. The last one is basically just testing Twig internals. I highly doubt there are any code paths through Timber being tested here that aren't already thoroughly tested elsewhere. Can you take a look and let me know if I'm missing anything?

**Comment by jarednova** [comment]
@acobster looks like versions of both had actually been ported over to `test-timber-post-collection.php`. I went ahead and removed the file in my most recent commit. I think we're on to final review here!

**Review by gchtr — APPROVED** [review]
This is looking good to me. We only need to document this in the Upgrade Guide, but I’ve already noted that in the todos in #2073. The Upgrade Guide is further ahead there, so we should do it there.

**Comment by acobster** [comment]
**SO SATISFYING.** :tada: :hocho:

**Comment by jarednova** [comment]
It's like losing fifty pounds, right? (or 1865 lines of code I guess)

**Pull request merged**
