### PR TITLE
2.x Check coding style

### PR DESCRIPTION
**Pull request by szepeviktor**
There should be at least 3 basic checks

- syntax
- **coding style**
- static analysis

### CODE REVIEW

**Comment by szepeviktor** [comment]
Currently we are several thousands violations away from WPCS.

Shouldn't we follow a modern coding standard?
https://github.com/Automattic/phpcs-neutron-ruleset ?

**Comment by jarednova** [comment]
> Currently we are several thousands violations away from WPCS.

You are totally correct @szepeviktor. This is one of our [final steps](https://github.com/timber/timber/projects/4#card-12836532) before we release 2.0. We've been holding off so that we don't hit a bunch of merge conflicts between 2.x and 1.x. To help get us there though, is there a current preferred tool for running/applying/checking? I notice you had `composer lint` in the Travis file on this PR

**Comment by szepeviktor** [comment]
Yes, "composer lint" equals "phpcs" (in composer.json)

The WordPress way is wpcs or neutron,
the OOP way is PSR-12 possibly with a more modern tool: https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/4502

**Comment by gchtr** [comment]
@szepeviktor Cool! That’s the missing step to automate coding standards! I’m no Travis expert, so I’m very happy that you provide us with the proper way to incorporate this 👍.

We added `composer lint` in #1933 and defined what Coding Standards to use in #1603. The Coding Standards are documented in https://github.com/timber/timber/blob/master/CONTRIBUTING.md#coding-standards, but as @jarednova mentioned, we will only apply them as on the last tasks for Timber 2.0.

We’ll see whether we will make use [Automattic/phpcs-neutron-ruleset](https://github.com/Automattic/phpcs-neutron-ruleset), depending on how well we can apply the standards we already defined. I’m a little wary about adding yet another dependency. Especially one that we don’t have much control over. Plus, the [Neutron standards](https://github.com/Automattic/phpcs-neutron-standard/blob/master/GUIDELINES.md) seem to have a lot of standards which would mean so much work for us just to create compatibility. But we could surely poke around and see what they have in there to make our lives easier 😉.

But Tools like [VariableAnalysis](https://github.com/sirbrillig/phpcs-variable-analysis) and [ImportDetection](https://github.com/sirbrillig/phpcs-import-detection) definitely look interesting!

For automation, `phpcs` recommends to use [`phpcbf`](https://github.com/squizlabs/PHP_CodeSniffer/wiki/Fixing-Errors-Automatically#using-the-php-code-beautifier-and-fixer).

**Comment by jarednova** [comment]
Just adding the **blocked** label for now. We can pick this up once we get the remaining Factories stuff in. From what I can tell, this looks like a clear/simple implementation so we only run once w Travis

**Comment by szepeviktor** [comment]
Very BIG 🍏 success.

**Comment by jarednova** [comment]
Oh wow, are we ready to pick this up? With #2592 I believe we can!

The specific code with this PR might be stale (with its Travis file) — but all the same ideas can be brought over to GH Actions. Any ✋ ? I think we should follow "le mieux est l'ennemi du bien" 🇫🇷 and start one level/piece at a time so the PR(s) stay managable and mergable.

**Comment by szepeviktor** [comment]
> The specific code with this PR might be stale (with its Travis file)

**ALL** my projects run on Travis CI.

```
Travis CI Travis CI Travis CI
Travis CI Travis CI Travis CI
Travis CI Travis CI Travis CI
```

**Comment by gchtr** [comment]
With #2592 being merged quite some time ago, we can close this one.

As always, big thanks to @szepeviktor for showing us how it can be done and holding us accountable for clean code and a modern setup 🙌.

**Pull request closed without merging**
