### PR TITLE
Twig deprecated features.

### PR DESCRIPTION
**Pull request by MouadDB**
Fixing 'Deprecated' notices like "Using the "Twig_Token" class is deprecated since Twig version 2.7, use "Twig\Token" instead."
https://twig.symfony.com/doc/2.x/deprecated.html

### CODE REVIEW

**Comment by gchtr** [comment]
Hey @MouadDB 

Thanks for your first contribution to Timber!

We’ve also seen the warnings about deprecated classes in Twig and we recently merged #1963 into the master branch to fix some of these. But I see in your pull request that we missed some of those:

`Twig_Loader_Filesystem` to `Twig\Loader\FilesystemLoader`
`Twig_Token` to `Twig\Token`
`Twig_Extension_Debug` to `Twig\Extension\DebugExtension`

And I also realized that we probably have to update the following code:

https://github.com/timber/timber/blob/b78e929ea65846b6c16e4c0af714b461019d672a/lib/Twig.php#L246-L265

When we call `$twig->getExtension('Twig_Extension_Core')`, we should probably use `$twig->getExtension('Twig\Extension\CoreExtension')` instead.

I created a new pull request #1977 to handle the differences and to resolve the outstanding conflicts with the master branch. As soon as that pull request is merged, this pull request should be merged automatically.

**Comment by jarednova** [comment]
Oh I am such a stupendous idiot and didn't realize that @gchtr already took care of what I flagged on #1977 — moving over there

**Comment by jarednova** [comment]
Looks like there was one piece of documentation not caught in #1977 — merging this one too

**Comment by MouadDB** [comment]
Thanks

**Pull request merged**
