### PR TITLE
Addition of WooCommerce2.md, which is a compilation of code from vari…

### PR DESCRIPTION
**Pull request by jake46a**
**Ticket**: # 

#### Issue
WooCommerce Integration.  A guide for those not so technically inclined.

#### Solution
Pulled information from 4 different guides and added some of my own code.  It is a working template that I do have.

#### Impact
None

#### Considerations
Was wondering about links to the working demo of this template, if that is allowed. Or I could scale down the template package and allow for download.

### CODE REVIEW

**Comment by jarednova** [comment]
Hi @jake46a thanks so much for the PR! There's obviously a lot here. I've yet to read the entire thing, but I have two quick thoughts to help things hopefully right-off-the-bat ...

1) **Title**: I'm thinking it would help to give people a better idea of what's in here rather than just "another version of what's already there." Perhaps: "WooCommerce: Step-By-Step Guide" or "WooCommerce Tutorial"?

2) **Length**: Could some of the code chunks be shortened by moving them into a gist? I'm thinking of that `base.twig` files (and perhaps some others) that are mostly copy-and-paste. We can also look at creating a JS thing in the docs for hiding/showing longer code snippets.

That's just my quick take. @gchtr has done the bulk of the docs work so I'd really like him to weigh-in for how he sees something as extensive as this working (but I think he's on vacation right now)

**Comment by jake46a** [comment]
Hi @jarednova 
You are more than welcome, it was a pleasure diving in and starting to give back. 
The Title, I like WooCommerce step by step.

As for the length, We can cut it down by giving them a link to install/download the template maybe with it in it? I can set up a repo here with a template with Timber, Bootstrap 4, all the files needed, taking out the bootstrap components and a few others not needed to run WooCommerce.  Then all they would need to do is install woocommerce and timber plugins, install template and go.

Just a thought - :)

**Comment by gchtr** [comment]
@jake46a @jarednova Cool stuff! I can look at this in August 😉.

**Comment by Levdbas** [comment]
We are going to close this since this PR is now pretty outdated. We discussed this and @gchtr mentioned that he had good luck implementing Woocommerce with timber in 2.0. So maybe he will be able to share that in the future in the fom of an updated guide.

**Pull request closed without merging**
