### PR TITLE
Fix #2773 (send empty extension for image with no extension)

### LINKED ISSUE #2773: [BUG] Missing extension for image
### Expected Behavior

Hi, there,

I use the Eventbrite API (https://www.eventbrite.com/platform/api#/reference/event/retrieve/retrieve-an-event) and import events (title, content, cover image, ...) into WordPress.

Eventbrite gives us an image URL with no extension.
It's a URL that resizes the image on the fly
The image extension is indeed a jpeg, but Timber (in the ImageHelpers class) can't find it.

### Actual behavior

I've made a modification in the pull request that follows, so as to ignore the extension if it doesn't exist, and thus avoid displaying an error.

### Steps to reproduce behavior

1. Retrieve event from API (eventbrite)
2. Import image with url
3. Display this image with timber

### Notes

_No response_

### What version of Timber are you using?

1.22

### What version of WordPress are you using?

6.2.2

### What version of PHP are you using?

8.1

### How did you install Timber?

Installed or updated Timber through Composer

### PR DESCRIPTION
**Pull request by Spidlace**
Related:

- #2773 

## Issue
Display error if image extension does not exist

### CODE REVIEW

**Comment by Levdbas** [comment]
As discussed yesterday, this is a small fix that we can safely include in a point release. This PR is based on the 1.x branch, so we will have to port this to 2.x first and maybe merge this in 1.x before making a final release there.

**Comment by Levdbas** [comment]
@timber/rangers , can you take a look at this PR if its ready for a merge?

**Comment by gchtr** [comment]
@timber/rangers I ported this over to 2.x and added a test in https://github.com/timber/timber/pull/2934.

**Comment by Levdbas** [comment]
Hi @Spidlace , thank you for your original PR. @gchtr just ported this to Timber 2 so this will ship in one of the next versions of Timber.

**Pull request closed without merging**
