### PR TITLE
992 post type labels

### PR DESCRIPTION
**Pull request by jarednova**
**Ticket**: #992 
**Reviewer**: @connorjburton 

#### Issue
Need an API to access post type information that matches other methods on Post

#### Solution
`{{ post.type }}` can store and return this data

#### Impact
If a user has a custom field named "type" they're gonna have a bad time

#### Usage
`{{ post.type }}` and the old method `{{ post.get_post_type }}` still work

#### Considerations
Should `{{ post.post_type }}` return this data too? At first I thought so, but then I changed my mind. Thoughts?

#### Testing
Tests included!

### CODE REVIEW

**Comment by jarednova** [comment]
I just caught a failing test, please hold on reviewing for now...

**Comment by fewerflatlands** [comment]
as you say, **If a user has a custom field named "type" they're gonna have a bad time** - in fact this appears to be a breaking change in 1.04... I've just had to downgrade to 1.03 as a result. any suggestions for a workaround?

**Comment by connorjburton** [comment]
We should probably change this to `post.post_type` @jarednova ?

**Comment by connorjburton** [comment]
Related #1057

**Comment by connorjburton** [comment]
We could also make this pluggable, so only add the `type` property if it doesn't already exist.

**Comment by fewerflatlands** [comment]
either of those (`post_type` rather than `type` or the conditional add) seem better than bulldozing any custom field called type... it's got to be a pretty common/likely field name, no?

**Comment by jarednova** [comment]
@connorjburton @fewerflatlands thanks for the heads-up on that. I agree and will work on a patch now

**Pull request merged**
