### PR TITLE
Set next and prev to use paginate_links array 

### PR DESCRIPTION
**Pull request by lggorman**
**Ticket**: 
**Reviewer**: @jarednova

#### Issue
The `Timber::get_pagination` function accepts a preferences array, which can include arguments like a custom base or format for the pagination links.  These args are then passed into the the paginate_links function, which generates the `pages` attribute of the pagination array.  However, the `next` and `prev` attributes of the array are generated separately, using `get_next_posts_page_link` and `previous_posts`, neither of which uses the prefs array.  So basically the issue is that if you try to pass custom args, they will not be incorporated into the `next` and `prev` links.

#### Solution
Instead of using `get_next_posts_page_link` and `previous_posts`, just get the next and prev links from the `pages` array generated by `paginate_links`. 

#### Impact
None

#### Usage
No changes

#### Considerations
--

#### Testing
Tests are included!

### CODE REVIEW

**Comment by jarednova** [comment]
Awesome – thanks @lggorman! I'll review this once the tests pass

**Comment by jarednova** [comment]
This is great @lggorman! With this gap patched, I'd still like you to think about the best API to interact with pagination; we can talk next week a little more about how this might take shape

**Comment by connorjburton** [comment]
Does this solve #671 ?

**Comment by lggorman** [comment]
@connorjburton Don't think so unfortunately -- this just sets next and prev to pull from that `pages` array, so if that's empty as well there's still going to be an issue.

**Pull request merged**
