### PR TITLE
Run CI on Graviton

### PR DESCRIPTION
**Pull request by szepeviktor**
an AMD microarchitecture
https://en.wikipedia.org/wiki/ARM_Cortex-A76#Neoverse_N1

Please see https://twitter.com/szepeviktor/status/1347000358455791616

### CODE REVIEW

**Comment by szepeviktor** [comment]
It seems like Travis has been disconnected from this repo 😿 
https://travis-ci.com/github/timber/timber/pull_requests

**Comment by jarednova** [comment]
Yeah, somehow we're "over our plan allotment" for build credits on OSS 🤯 . I've got a support thread going with them to figure out how to get our credits reset.

**Comment by szepeviktor** [comment]
Simply ask them: https://twitter.com/szepeviktor/status/1347170306813779982

**Comment by jarednova** [comment]
Afraid we get errors here, see the build log: https://travis-ci.com/github/timber/timber/jobs/497464880

... python-related?

**Comment by szepeviktor** [comment]
Ubuntu dropped it.
https://askubuntu.com/a/422976
I'm not sure we need it at all.
Let's require `software-properties-common` instead!

**Comment by jarednova** [comment]
That did it! Looking at the build times it seems like about a ~10% or so boost in speeds:

https://travis-ci.com/github/timber/timber/builds/222688799

is that the expected impact?

**Comment by szepeviktor** [comment]
> is that the expected impact?

I'm no hardware guy.
Amazon must have had a reason to introduce Graviton!

**Comment by jarednova** [comment]
Hey, it ain't nuthin — I'll take it!

**Pull request merged**
