### PR TITLE
2.x Update documentation for Getting Started

### PR DESCRIPTION
**Pull request by gchtr**
## Issue

The [Getting Started](https://timber.github.io/docs/getting-started/) section of the documentation needs some updates because of the changes in 2.x.

## Solution

I went back and forth with how structured a Getting Started guide. What to start with? When to introduce the concept of the Context? How to teach about stuff works in Twig? I came up with an approach that looks like this:

A new [Index](https://github.com/timber/timber/blob/2.x-docs-getting-started/docs/v2/index.md) that will be the starting point for the Timber documentation. Here, I also added a section about [Who is Timber for?](https://github.com/timber/timber/blob/2.x-docs-getting-started/docs/v2/index.md#who-is-timber-for) to clarify when it is the right tool for the job. It took these inputs mostly from Jared’s [Pressing Matters Podcast episode](https://pressingmatters.fm/episodes/27-talking-timber-jared-novack/).

1. [Introduction](https://github.com/timber/timber/blob/2.x-docs-getting-started/docs/v2/getting-started/introduction.md) – Starts with some very basic traditional WordPress code and slowly moves up to basic concepts of Timber, while learning about the Context and the Timber philosophy in the process.
2. [Template Inheritance and Includes](https://github.com/timber/timber/blob/2.x-docs-getting-started/docs/v2/getting-started/template-inheritance-and-includes.md) – This chapter is mostly about Twig and to compose templates with inheritance and using Twig’s include to structure template files.
3. [A single post](https://github.com/timber/timber/blob/2.x-docs-getting-started/docs/v2/getting-started/a-single-post.md) – Looks at how you would set up a blog post with Timber, what the different variable means and where they come from.
4. [A post archive](https://github.com/timber/timber/blob/2.x-docs-getting-started/docs/v2/getting-started/a-post-archive.md) – Introdudes collections of posts and queries.

And there are some other changes:

- I deleted the [Twig Tools Guide](https://timber.github.io/docs/getting-started/twig-tools/), because to me, showing related projects doesn’t really fit into a Getting Started section for me. Instead, I moved it to the [Twig Cookbook](https://github.com/timber/timber/blob/2.x-docs-getting-started/docs/v2/guides/cookbook-twig.md#twig-tools).
- I deleted the [Video Tutorials Guide](https://timber.github.io/docs/getting-started/video-tutorials/) for now. Not because I don’t like tutorial videos, but because their content is a little outdated for version 2. It would be great if we could complement the written tutorials with a video or multiple videos.
- I moved some of the relevant content in the [Setup Guide](https://timber.github.io/docs/getting-started/setup/) to the new [Installation Guide](https://github.com/timber/timber/blob/2.x-docs-getting-started/docs/v2/installation/installation.md#use-the-starter-theme). For the Starter Theme, we can use `composer create-project` instead of `composer install`.

In the Introduction, I mention a [Tutorial Theme](https://github.com/timber/timber/blob/2.x-docs-getting-started/docs/v2/getting-started/introduction.md#tutorial-theme). That doesn’t exist yet. Before I add a repository for this, I wanted to see what you think about the Getting Started Guides.

- Did I miss something important for an introduction to Timber?
- Is this the right order for introducing concepts?
- Is the philosophy and mindset behind Timber prominent enough? Well, it’s not explicit, but I tried to describe it here and there.

## Impact

An up-to-date introduction to Timber.

## Usage Changes

None.

## Considerations

- We can think about how the first page of the documentation (the [Index](https://github.com/timber/timber/blob/2.x-docs-getting-started/docs/v2/index.md)) is going to be similar to the [README](https://github.com/timber/timber/blob/master/README.md) of the GitHub repository.
-  It’s a pity that tutorials like [the one on TutsPlus](https://code.tutsplus.com/series/kick-start-wordpress-development-with-twig--cms-974) or [the one on CSS-Tricks](https://css-tricks.com/timber-and-twig-reignited-my-love-for-wordpress/) will become a little bit outdated. What do we do about those?

## Testing

No unit tests necessary. But I should still test out the snippets manually.

## Todo

- [x] Set up Getting Started Tutorial theme as a GitHub repository.
- [x] ~Test out code snippets manually.~ Will be completed in #2278

### CODE REVIEW

**Comment by jarednova** [comment]
Thanks @gchtr! I started to go through the details tonight, but I'm running out of steam. I'll pick this up tomorrow to get you any feedback and thoughts on next steps!

**Comment by gchtr** [comment]
@jarednova Cool man, thanks for spotting all those little details! 👀

I recently figured we can [remove specific Twig versions](https://github.com/timber/timber/pull/2259/commits/064adb434744a89b8605d49111e6f4561b3ba9b1) from links in to the Twig documentation. It will redirect to the latest version automatically.

I’m going to finish the remainig todos.

**Comment by gchtr** [comment]
Okay, so I added a new [timber/getting-started-theme](https://github.com/timber/getting-started-theme) repository and added some more information for the introduction in [`8823843`](https://github.com/timber/timber/pull/2259/commits/8823843f2dfffaab7edc15bfa85572588e852f3a).

I figured I can’t test the code snippets yet, because the `2.x` branch is at a state that is not usable yet. I created a separate issue for this in #2278.

So this is basically ready to merge.

**Comment by jarednova** [comment]
Excellent, let's do it! Thanks for making that new repo

**Pull request merged**
