### PR TITLE
Add possibility to disable cropping in resize function #1332

### PR DESCRIPTION
**Pull request by idflood**
#### Issue
https://github.com/timber/timber/issues/280
https://github.com/timber/timber/issues/1332

#### Solution
Allow passing `false` as third argument of the resize function. With this the image will be resized to fit in the specified dimension while preserving the original aspect ratio and without cropping.

#### Impact
Adds less than 5 lines of code : )

#### Usage Changes
The 3rd parameter to the resize can be set `false` to disable cropping.

    

#### Considerations
The current code had a condition `if (!$crop)` where I add the crop attributes (Line 110). Not sure if it was really used since it was not a documented option. But it was probably there for a reason I can't imagine.

### CODE REVIEW

**Comment by palmiak** [comment]
@idflood if you would generate:
```
<img src="{{ product.thumbnail|resize(1000,500,false) }}" />
```
what would be the file name? Wouldn't it be a duplicate of the name:
```
<img src="{{ product.thumbnail|resize(1000,500) }}" />
```

Also maybe it would be better to change the third param to array as I mentioned https://github.com/timber/timber/issues/1435#issuecomment-450886255 . From what I remember @gchtr is also a big fan of params as arrays. 

It would open a way to create new functionality like quality, upscale (or not) etc etc.

**Comment by gchtr** [comment]
My opinion on how to define how images are processed with arguments and an overview of what needs to considered when touching image functions can be found here: https://github.com/timber/timber/issues/857#issuecomment-364782702.

Recently I’ve been working on other things and this became a little stale. But I think we could tackle it now (meaning, we don’t have to wait for 2.x to come out) and add argument arrays while keeping backwards compatibility with the current parameters. We keep hitting the same end and argument arrays seem to be a way to go. I’m happy to hear about other opinions or better solutions.

@idflood We can definitely use your logic for this, just with another API.

Does somebody want to take this over or do you want to leave it to me? I think I could find some time soon.

**Comment by palmiak** [comment]
@gchtr I would be interested in changing the third parameter to array + backward compatibility. It would be a great start and base for some further stuff:

If I'm thinking correctly this will need:
- checking is the third param is array, string or none
- changing the name generator function (make it more universal for all the future stuff)

I'll create an pull request to discuss the second part.

Having this we'll be able to add:
- crop / no cropp
- upscale or not
- quality per resize

**Comment by gchtr** [comment]
@palmiak I’d be happy if you could take this over! I have some big updates to the documentation I’m still working on.

I think I wouldn’t change only the third parameter to an array – I would change it so that `resize()` accepts only a single argument array, including parameters for width and height. So instead of 

> * checking is the third param is array, string or none

I’d go for 

* Checking if param for resize is an arguments array.

For backwards compatibility, we can still check what’s coming in. For version 1.x, we could still keep the second parameter. In version 2.x, we’d kick that out as well.

> * changing the name generator function (make it more universal for all the future stuff)

I didn’t think about file names yet, but I think you’re on the right track there!

> I'll create a pull request to discuss the second part.

Good idea. A pull request with a `wip` label can help others to see what’s being worked on and give them a chance to chip in with comments and ideas 👍.

> Having this we'll be able to add:
> 
> * crop / no cropp
> * upscale or not
> * quality per resize

In the future, we should be able to control all necessary image manipulations:

```php
<img src="{{ img|resize({
    width: 300,
    height: 200,
    quality: 75,
    allow_upscale: false,
    fit: true,
    crop: 'something',
    letterbox: '#fff',
    format: 'webp',
    profile: 'rgb'
}) }}">
```

**Comment by Levdbas** [comment]
Hi @idflood , thank you for your ticket back then. Since we are not going to actively put new features in Timber 1, I am going to close your PR. I do going to add this to a new ticket where we track several requests regarding Image manipulation so we can decide how we will handle images in upcoming Timber 2 updates.

**Pull request closed without merging**
