### PR TITLE
2x. Update composer.json

### PR DESCRIPTION
**Pull request by gchtr**
Fix some info in composer.json that will be displayed on https://packagist.org/packages/timber/timber and other places.

### CODE REVIEW

**Review by Levdbas — COMMENTED** [review]
Looks good to me! Maybe add "WordPress" to the keywords as well?

**Comment by jarednova** [comment]
@Levdbas @gchtr @nlemoine — updated! Leaving for you guys to add whatever contact info you want to include (email? homepages?) or give a 👍 if you prefer to leave with just your name. Remember — your names will live in infamy!

**Comment by Levdbas** [comment]
Tnx @jarednova , added my details!

**Comment by gchtr** [comment]
Added my info as well 😊.

@nlemoine Do you also want to add yours?

**Pull request merged**
