### PR TITLE
2.x Update function signature for Term::posts()

### PR DESCRIPTION
**Pull request by gchtr**
**Tickets:**

- https://github.com/timber/timber/pull/1931
- https://github.com/timber/timber/pull/2208
- https://github.com/timber/timber/pull/2208#pullrequestreview-369092394

## Issue

I almost forgot again about what we discussed in the linked Tickets above.

## Solution

This pull request updates the function signature for `Term::posts()` to use the same pattern that we use for a lot of other functions.

```php
// Old
function posts( $numberposts_or_args = 10, $post_type_or_class = 'any', $post_class = '' );

// New
function posts( $query_args = [] );
```

## Impact

There’s no backwards compatibility, but I added checks when the wrong parameters are passed.

Because I changed the `Term::posts()` function, I had to update the `Term::get_post()` function as well. This will trigger a doing-it-wrong notice now. Because we can no longer support the former arguments, this is not a formal deprecation anymore.

## Usage Changes

**Old usage**

In PHP:

```php
$genre->posts( -1, 'book' );
```

And in Twig:

```twig
{% for book in genre.posts(-1, 'book) %}
```

**New usage**

In PHP:

```php
$genre->posts( [
    'post_type'     => 'book',
    'post_per_page' => -1,
    'orderby'       => 'menu_order'
] );
```

And in Twig:

```twig
{% for book in genre.posts({
    post_type: 'book',
    posts_per_page: -1,
    orderby: 'menu_order'
}) %}
```

## Considerations

None.

## Testing

There are tests that are still failing because of the class parameter that is not supported anymore. We should probably wait until the post factory is finished and update the tests then.

### CODE REVIEW

**Comment by jarednova** [comment]
The code looks good. As for the three failing tests, here they are for easy reference:

```
1) TestTimberTerm::testGetPostsNew
Failed asserting that Timber\Post Object (...) is an instance of class "TimberPostSubclass".

/srv/www/timber/tests/test-timber-term.php:222

2) TestTimberTerm::testPostsWithCustomPostTypeAndCustomClassMap
Failed asserting that Timber\Post Object (...) is an instance of class "TimberPostSubclass".

/srv/www/timber/tests/test-timber-term.php:279

3) TestTimberTerm::testPostsWithCustomPostTypePageAndCustomClass
Failed asserting that Timber\Post Object (...) is an instance of class "page".

/srv/www/timber/tests/test-timber-term.php:309
```

... looks pretty straightforward to solve in conjunction with Factories

**Comment by acobster** [comment]
@jarednova this is looking good to me, but I'm wondering if you think adding an `$options` arg for forwarding to `Timber::get_posts()` would make sense here?

**Comment by jarednova** [comment]
@acobster agreed, while things are fresh and open let's add that in.

**Comment by gchtr** [comment]
> @jarednova this is looking good to me, but I'm wondering if you think adding an `$options` arg for forwarding to `Timber::get_posts()` would make sense here?

Cool, I added the parameter in https://github.com/timber/timber/pull/2258/commits/263bed9ce304c3992e899e1c916139307fe06c7a.

**Review by acobster — APPROVED** [review]
We've discussed these changes over on #2316. Merging.

**Pull request merged**
