### PR TITLE
Do not distribute development files

### LINKED ISSUE #1147: Clean up dependencies before release
Would it be possible to remove all files (tests, docs etc.) from the `vendor` directory during the plugin release process?

### PR DESCRIPTION
**Pull request by szepeviktor**
Fixes #1147

### CODE REVIEW

**Comment by jarednova** [comment]
@szepeviktor , thanks for this one! I'm a bit unfamiliar with `.gitattributes` and `export-ingore`. When it talks about these ["not being added to archive files"](https://git-scm.com/docs/gitattributes#_code_export_ignore_code) which distributions would this affrect? Does Composer/Packagist not distribute these? or is this about a different distribution point/source?

**Comment by szepeviktor** [comment]
> Does Composer/Packagist not distribute these?

No.

- GitHub ZIP
- Composer package

**Comment by szepeviktor** [comment]
e.g. https://github.com/szepeviktor/phpcs-psr-12-neutron-hybrid-ruleset

https://github.com/szepeviktor/phpcs-psr-12-neutron-hybrid-ruleset/archive/master.zip

**Comment by jarednova** [comment]
Excellent, thanks for the clarification!

**Comment by szepeviktor** [comment]
Happy to contribute to such a high quality project :)

**Comment by jarednova** [comment]
Stop it! I'm blushing

**Pull request merged**
