### PR TITLE
Whoops! Use the suggested syntax

### PR DESCRIPTION
**Pull request by jarednova**

### CODE REVIEW

**Comment by szepeviktor** [comment]
Could it be that I'm wrong for years? I use `phpenv version-name` in many repos!

https://github.com/phpenv/phpenv/blob/master/libexec/phpenv-version-name

**Comment by szepeviktor** [comment]
Found!

`- php: 5.6.40` -> `- php: 5.6`
then you'll get the latest version

kép

**Comment by jarednova** [comment]
Nice! That makes a lot of sense given how `php: 7.4`, etc. operates

**Comment by szepeviktor** [comment]
All green 🍏

**Pull request merged**
