### PR TITLE
Add support for public query_vars

### PR DESCRIPTION
**Pull request by xavivars**
**Ticket**: https://github.com/timber/timber/issues/1249
**Reviewer**: @ 

#### Issue
Problem with pagination and usage of query vars

#### Solution
Take query_vars into account when deciding if pages need to be removed

#### Impact
Pagination

#### Considerations
I've also removed tests I added in the past when working on some other pagination issues, as one of them is in fact doing the wrong thing.

#### Testing
Unit tests are included.

### CODE REVIEW

**Comment by xavivars** [comment]
I've faced some problems locally with some tests: `testWPMLurlRemote` (in test-timber-image-resize.php) is failing for me, and I can't see how that test could have ever passed. However, it seems the tests is not being executed in Travis, as GD-dependant tests are ignored.

**Comment by xavivars** [comment]
I've identified a better way to handle this. I had to rewrite most of `paginate_links`, as when looking at it the current logic didn't have much sense: fragment (`#`) being added before the query strings, trailing/untrailingslashit after adding both fragment and query strings....

I'm making sure all tests pass now, and I'll commit the new code.

**Comment by xavivars** [comment]
I've done another round of refactor, now changing more stuff (even some tests that, IMHO, were wrongly setup). But I'd like to leave it for a second round of review in case this one gets merged.

**Comment by jarednova** [comment]
So much cleaner, thanks @xavivars — and tests too!!!!

**Pull request merged**
