### PR TITLE
2.x Update Upgrade Guide with Twig deprecations

### PR DESCRIPTION
**Pull request by gchtr**
**Ticket**: #2482

We should mention that Twig also has some deprecations.

I didn’t mention all the relevant deprecations, like the filter or the spaceless tag. Let’s see what issues come by people who find it hard to find a solution.

### CODE REVIEW

**Comment by jarednova** [comment]
> I didn’t mention all the relevant deprecations, like the filter or the spaceless tag. Let’s see what issues come by people who find it hard to find a solution.

Only so much we can do. I think it's best to point to the official source rather than re-writing it (and risk being out of sync)

**Review by jarednova — APPROVED** [review]

**Comment by Levdbas** [comment]
It might me good to add some examples. These are the two that I had some issue finding out myself. Might help other if added to the docs.

**Spaceless**
```twig
{% apply spaceless %}

{% endapply %}
```


**Apply**
```twig
{% apply apply_filters('your_filter_name') %}

{% endapply %}
```

**Comment by gchtr** [comment]
Thanks @Levdbas for the hint. I love inputs like these. They will definitely help others. If you find more cases where better docs might be needed, let me know. Or you could add them in a pull request yourself, if you like.

I added the changes in https://github.com/timber/timber/pull/2565/commits/86b54abdc57cd9d6d4b0e821851d5a7cee6c66bc and also found some instances in the 2.x guides that were still using the old format.

@jarednova Could you give this another review, please?

**Review by jarednova — APPROVED** [review]
This looks good. Thanks for minding all those finishing touches @gchtr and @Levdbas — I learned something!

**Comment by jarednova** [comment]
@gchtr I'll pass back to you for final merge!

**Pull request merged**
