### PR TITLE
2.x Clean up post preview

### PR DESCRIPTION
**Pull request by gchtr**
## Issue

Functions that were deprecated in 1.x can be removed in 2.x. `Post::get_preview()` is one of these candidates.

## Solution

- Delete the method and update tests.
- Add an `@api` tag to the `PostPreview` class so that it appears in the documentation, because currently, it’s missing.

## Impact

Breaking change.

## Usage Changes

`Post::preview()` or `new PostPreview()` should be used.

## Considerations

When using `$preview = new PostPreview()` in PHP, you’ll have to do `(string) $preview` for it to be converted to string (so that `__toString()` kicks in), because `PostPreview::run()` is protected. I don’t like this API very much. Are there better solutions?

- `$preview->to_string()`?
- `$preview->get()`?
- others?

## Testing

There’s a failing test because when we use an empty string as the value for the `readmore` option, a Readmore link will still be added. I’m not sure whether this behavior was introduced only lately, because the tests tell us that an empty string should probably be evaluated as `false`, resulting in no link being added. @jarednova I would be glad if you could have a look.

Oh, and maybe ignore whitespace when looking at the changes, because I fixed a wrong indentation in the tests, too.

### CODE REVIEW

**Comment by jarednova** [comment]
@gchtr fixed the test! Just a problem with `readmore` vs. `read_more` as the name for that argument. Two follow along questions:

- Should we change `PostPreview::$readmore` to `PostPreview::$read_more` so that's universal?
- Should we make `readmore` an alias of `read_more`?

As for your question, when I use that value w/o the `(string)` it still works because of `__toString()`. Checkout e86e941 for how I modified the test to see this in action. Is that what you're referring to? or a different use-case?

**Comment by gchtr** [comment]
@jarednova 

> Just a problem with `readmore` vs. `read_more` as the name for that argument

😅 Phuu, glad it’s just that.

>     * Should we change `PostPreview::$readmore` to `PostPreview::$read_more` so that's universal?

Yes, please!

>     * Should we make `readmore` an alias of `read_more`?

Not necessarily. I probably used `readmore` instead of `read_more` because the deprecated `Timber\Post::get_preview()` used `readmore` as a parameter name. I had a window open with that function as a reference for the parameter order so I could change the tests.

I think this shouldn’t be a problem when we only use `read_more` in the code, in the inline documentation as well as the documentation.

> As for your question, when I use that value w/o the `(string)` it still works because of `__toString()`. Checkout [16450b0](https://github.com/timber/timber/commit/16450b0b270fa9ebfa117f36edb1c346ce4bfca2) for how I modified the test to see this in action. Is that what you're referring to? or a different use-case?

Okay, in that case I misunderstood it.

Do you want to make the final over this with fixing `readmore` → `read_more`, or do you want me to do it?

**Comment by jarednova** [comment]
> Do you want to make the final over this with fixing readmore → read_more, or do you want me to do it?

Go ahead and take it home — then LTGM!

**Comment by gchtr** [comment]
Cool, I’ll see what I can do.

From #1817, there are two more task:

- Rename `PostPreview` to `PostExcerpt` (in https://github.com/timber/timber/issues/1817)
- Maybe add tests for #1345 and fix it (in https://github.com/timber/timber/issues/1817#issuecomment-470706883)

**Comment by gchtr** [comment]
Okay, I made progress here.

- I changed all instances of `readmore` to `read_more`.
- I renamed all relevant instances of "Preview" to "Excerpt".
- I optimized the code a bit to make it more readable, like [here](https://github.com/timber/timber/pull/2365/commits/f5afa7432db9521badc9813a372b2f013d4e5427) and [here](https://github.com/timber/timber/pull/2365/commits/a0b69f121f89552587ff94b3c8953b3530130eb2).
- Deprecated the `timber/post/preview/read_more_class` filter and added `timber/post/excerpt/read_more_class` instead in [`4c664cc` (#2365)](https://github.com/timber/timber/pull/2365/commits/4c664cc26813752edfbcda6e827b0d872e012a40).
- I found that the `timber/post/get_preview/read_more_link` filter that was removed in https://github.com/timber/timber/commit/a01086582ad0315ca1c90ec02d08a506f4f95d0e, so I added it back, deprecated it and added `timber/post/excerpt/read_more_link` instead in [`d36989b` (#2365)](https://github.com/timber/timber/pull/2365/commits/d36989b12cfbfdef9615dde47aafa94196cc449e).

And then there’s an additional pull request in #2375.

@jarednova I’d be glad if you could have a look at this.

**Review by jarednova — APPROVED** [review]
I found just a few tiny tweaks in 2a638bb. Will merge once those tests clear!

**Comment by jarednova** [comment]
@gchtr all green over here! I'll let you do the honors ...

**Comment by gchtr** [comment]
🙌

**Comment by jarednova** [comment]
Niiiiiiiiiiiiiiiiiice

**Pull request merged**
