### PR TITLE
codecov should make tests fail

### PR DESCRIPTION
**Pull request by szepeviktor**
See https://github.com/codecov/codecov-bash/blob/master/codecov#L145

That stray "coveralls" was there for 5 months!

"after_success" executes first.

### CODE REVIEW

**Comment by szepeviktor** [comment]
Why doesn't PR-s got built?

**Comment by szepeviktor** [comment]
My CI https://travis-ci.org/github/szepeviktor/timber/builds/696707899

**Comment by szepeviktor** [comment]
> No code coverage driver available

phpunit depends on `phpunit/php-code-coverage:^6` which does not support pcov!

https://github.com/sebastianbergmann/php-code-coverage/blob/master/ChangeLog.md#700---2019-02-01

Could we upgrade to phpunit v8?

**Comment by jarednova** [comment]
thanks @szepeviktor! Now that jobs run so much quicker w/ speedy 😉  I've enabled the PR builds. 

As for PHP Unit — WordPress unit tests are limited to 7.x:
https://make.wordpress.org/core/handbook/testing/automated-testing/phpunit/

Why? That'd be a question for the WordPress Gods.

**Comment by jarednova** [comment]
@szepeviktor I think I need your help understanding this PR better. I think what you're showing is we had an unrecognized test failure with `php-code-coverage` and PCOV; but that was masked based on the travis build order.

We want to use PCov b/c it's way faster, but that's limited by the PHPUnit version. Which (if I'm following you here) means we need to look at following this article:

https://dev.to/swashata/setup-php-pcov-for-5-times-faster-phpunit-code-coverage-3d9c

... to properly run PHPUnit 7 w PCOV?

**Comment by szepeviktor** [comment]
# 🎉 
@jarednova We've got some phpunit activity :) :) :)

**Comment by jarednova** [comment]
awesome, we got this!

**Pull request merged**
