### PR TITLE
2.x Carbon Fields integration

### PR DESCRIPTION
**Pull request by nlemoine**
Hello,

Following up on #2397, I added Carbon Fields (`^3.0`) integration.

### CODE REVIEW

**Comment by acobster** [comment]
Thanks @nlemoine ! I haven't looked at this in detail yet but at first glance it looks pretty thorough, with tests and everything! Couple initial questions:

* Is this the kind of thing that you'd expect to have documentation for? I'm not super familiar with Carbon Fields but my understanding is it's an alternative to ACF, which we do have a [guide](https://timber.github.io/docs/guides/acf-cookbook/) for.
* Since you noted this is WIP, should I mark this PR as a draft? (or are you able to? not sure)

**Comment by nlemoine** [comment]
> Is this the kind of thing that you'd expect to have documentation for?

Actually, I'm trying to move Timber toward a unified "custom fields/meta" API guide more than a specific ACF or Carbon fields guide (see discussion in #2397). The goal is to have the same API for the meta, even when they are handled by different plugins.

Depending on Timber team decisions, docs will probably need to be updated. 

> Since you noted this is WIP, should I mark this PR as a draft?

It's marked as WIP because I had not implemented the "complex" field (which the Carbon Fields equivalent for repeater/flexible) yet. This should be ok now and ready to merge.

The tests pass but I didn't use Carbon Fields since quite a time. It would be great if someone with a better experience on that plugin could have a look (@vvasilev-, @jorostoyanov ?).

**Comment by gchtr** [comment]
> Actually, I'm trying to move Timber toward a unified "custom fields/meta" API guide more than a specific ACF or Carbon fields guide (see discussion in #2397). The goal is to have the same API for the meta, even when they are handled by different plugins.

A quick note here before I look in your pull requests in more detail. A general custom field guide exists in the [Custom Fields Guide](https://timber.github.io/docs/v2/guides/custom-fields/) for Timber v2. Integrations have separate guides, like [ACF](https://timber.github.io/docs/v2/integrations/advanced-custom-fields/).

If you’d like to build on those or improve them, you’re very welcome to do so.

**Comment by nlemoine** [comment]
> If you’d like to build on those or improve them, you’re very welcome to do so.

That's what I'm trying to do 😉  But I can't write docs until you make decisions on what's discussed in #2397 (transformed values or not, enabled by default or not, feedback on the proposed API, etc.).

I'm not sure to understand your expectations. Could you clarify them?

**Comment by gchtr** [comment]
> That's what I'm trying to do 😉 But I can't write docs until you make decisions on what's discussed in #2397 (transformed values or not, enabled by default or not, feedback on the proposed API, etc.).

Ok, I see! I’ll surely look at #2397 soon. I just wanted to make sure that you don’t start working on a general documentation for custom fields that already exists.

> I'm not sure to understand your expectations. Could you clarify them?

I have no expectations so far 😊. I only meant that if you think that a certain topic about custom fields is not documented well enough, you’re very welcome to contribute.

But I see that you already have a clear idea on what needs to be updated after we made decisions in #2397, so that’s great!

**Comment by nlemoine** [comment]
> I have no expectations so far 😊. I only meant that if you think that a certain topic about custom fields is not documented well enough, you’re very welcome to contribute.

No worries, docs are great 👍  I'm only proposing to rethink some parts of the meta API and this obviously might lead to docs changes.

**Comment by MartinPL** [comment]
Any news here :eyes:

**Comment by Levdbas** [comment]
Hi everyone, the core team decided that we are not going to actively introduce more integrations for now. This includes @nlemoine 
's Carbon fields integration. We highly encourage anyone to make a separate integration based on the codebase in this request. We will be more then happy to link in in our readme file as a related project.

**Pull request closed without merging**
