### PR TITLE
fixes #1625 - WMPL Image resize url issue

### LINKED ISSUE #1625: WPML + Image resize issues
Timber 1.5.2, Wordpress 4.9, PHP 5.6

Using the latest version of WPML on a translated page the resized images' urls have a trailing language query string i.e `/?lang=fr`.
This causes the images not to display and output the following error:
```
notice: 
Undefined index: extension in /app/wp-content/plugins/timber-library/lib/ImageHelper.php on line 386
Call Stack:    0.0013     239376   
1. {main}() /app/index.php:0    0.0013     239800   
2. require('/app/wp-blog-header.php') /app/index.php:17    1.3295   13947168   
3. require_once('/app/wp-includes/template-loader.php') /app/wp-blog-header.php:19    1.3515   13900384   
4. include('/app/wp-content/themes/made_ioc/page.php') /app/wp-includes/template-loader.php:74    2.5708   15274152   
5. Timber\Timber::render() /app/wp-content/themes/made_ioc/page.php:137    2.5708   15274296

(...)
```

I'm resizing the images using the `resize` filter in a Twig template.

### PR DESCRIPTION
**Pull request by Kwapi**
**Ticket**: #1625  

#### Issue
Resized images on WPML-translated pages have urls that contain the language query string which prevents them from displaying and throws an error.

#### Solution
WMPL overwrites `home_url()` therefore using `site_url()` is safer

### CODE REVIEW

**Comment by jarednova** [comment]
Thanks for this PR @Kwapi. I made a change to one of the tests to resolve the error but still (hopefully) stay true to the issue in #1513 and #1520. Is there any WPML user who can give this a second look to confirm that this PR works in yr setup?

**Comment by njbarrett** [comment]
Unfortunately this change seems to break installs where WP is installed in a different directory, e.g Bedrock.
For example my URLs in 1.7 now read:
`/wp/app/uploads/2018/02/7129c2548a7a9de76150aa03bec73424.jpg`
But in 1.6 they read:
`/app/uploads/2018/02/7129c2548a7a9de76150aa03bec73424.jpg`

I don't even have WPML installed on this particular site.

**Comment by jarednova** [comment]
@njbarrett Frak. Thank you for the heads-up. Do you happen to know if bedrock supplies any kind of environment info that would let us test for it?

**Comment by njbarrett** [comment]
@jarednova sorry for the delay replying here. Basically if `WP_SITEURL` is different to `WP_HOME` I think this issue will occur. Perhaps a way to define where the uploads folder is might help.

**Pull request merged**
